---
# vars file for jaredhocutt.homelab.authentik

authentik_postgres_db_name: authentik
authentik_postgres_user: authentik

###############################################################################
# Envrionment Variables
###############################################################################

authentik_env_vars_base:
  AUTHENTIK_POSTGRESQL__HOST: "{{ authentik_name }}-postgres"
  AUTHENTIK_REDIS__HOST: "{{ authentik_name }}-redis"

authentik_postgres_env_vars_base: {}

authentik_redis_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

authentik_secrets_base:
  authentik_postgres_db_name: "{{ authentik_postgres_db_name }}"
  authentik_postgres_user: "{{ authentik_postgres_user }}"
  authentik_postgres_password: "{{ authentik_postgres_password }}"
  authentik_secret_key: "{{ authentik_secret_key }}"

authentik_container_secrets_base:
  - authentik_postgres_db_name,type=env,target=AUTHENTIK_POSTGRESQL__NAME
  - authentik_postgres_user,type=env,target=AUTHENTIK_POSTGRESQL__USER
  - authentik_postgres_password,type=env,target=AUTHENTIK_POSTGRESQL__PASSWORD
  - authentik_secret_key,type=env,target=AUTHENTIK_SECRET_KEY

authentik_worker_container_secrets_base:
  - authentik_postgres_db_name,type=env,target=AUTHENTIK_POSTGRESQL__NAME
  - authentik_postgres_user,type=env,target=AUTHENTIK_POSTGRESQL__USER
  - authentik_postgres_password,type=env,target=AUTHENTIK_POSTGRESQL__PASSWORD
  - authentik_secret_key,type=env,target=AUTHENTIK_SECRET_KEY

authentik_postgres_container_secrets_base:
  - authentik_postgres_db_name,type=env,target=POSTGRES_DB
  - authentik_postgres_user,type=env,target=POSTGRES_USER
  - authentik_postgres_password,type=env,target=POSTGRES_PASSWORD

authentik_redis_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
authentik_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ authentik_name }}.rule
    value: Host(`{{ authentik_traefik_host }}`)
  - key: traefik.http.routers.{{ authentik_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
authentik_container_labels_base: "{{ authentik_traefik_enable | ternary((authentik_container_labels_traefik | items2dict), {}) }}"

authentik_worker_container_labels_base: {}

authentik_postgres_container_labels_base: {}

authentik_redis_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

authentik_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ authentik_name }}-postgres.service
    Requires={{ authentik_name }}-redis.service
    After={{ authentik_name }}-postgres.service
    After={{ authentik_name }}-redis.service
authentik_quadlet_options_base: "{{ common_quadlet_options_base + authentik_quadlet_options_base_custom }}"

authentik_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"

authentik_redis_quadlet_options_base: "{{ common_quadlet_options_base }}"
