---

- name: Stop services
  ansible.builtin.systemd:
    name: "{{ item}}"
    state: stopped
  become: true
  failed_when: false
  loop:
    - "{{ archiveium_name }}.service"
    - "{{ archiveium_name }}-cron.service"
    - "{{ archiveium_name }}-meilisearch.service"
    - "{{ archiveium_name }}-redis.service"
    - "{{ archiveium_name }}-minio.service"
    - "{{ archiveium_name }}-postgres.service"

- name: Destroy containers
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ archiveium_name }}"
    - "{{ archiveium_name }}-cron"
    - "{{ archiveium_name }}-meilisearch"
    - "{{ archiveium_name }}-redis"
    - "{{ archiveium_name }}-minio"
    - "{{ archiveium_name }}-postgres"

- name: Destroy secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    state: absent
  become: true
  no_log: true
  loop: "{{ archiveium_secrets_base | combine(archiveium_secrets, recursive=True) | dict2items }}"

- name: Destroy volumes
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ archiveium_volume_config }}"
    - "{{ archiveium_postgres_volume_data }}"
    - "{{ archiveium_minio_volume_data }}"
    - "{{ archiveium_redis_volume_data }}"
    - "{{ archiveium_meilisearch_volume_data }}"

- name: Destroy network
  containers.podman.podman_network:
    name: "{{ archiveium_name }}"
    state: absent
  become: true

- name: Cleanup quadlet files
  ansible.builtin.file:
    path: /etc/containers/systemd/{{ item }}
    state: absent
  become: true
  loop:
    - "{{ archiveium_name }}.container"
    - "{{ archiveium_name }}-cron.container"
    - "{{ archiveium_name }}-meilisearch.container"
    - "{{ archiveium_name }}-redis.container"
    - "{{ archiveium_name }}-minio.container"
    - "{{ archiveium_name }}-postgres.container"
    - "{{ archiveium_volume_config }}.volume"
    - "{{ archiveium_postgres_volume_data }}.volume"
    - "{{ archiveium_minio_volume_data }}.volume"
    - "{{ archiveium_redis_volume_data }}.volume"
    - "{{ archiveium_meilisearch_volume_data }}.volume"
    - "{{ archiveium_name }}.network"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
