---
# defaults file for jaredhocutt.homelab.homarr

homarr_name: homarr

homarr_image: ghcr.io/homarr-labs/homarr
homarr_image_tag: latest

homarr_volume_data: "{{ homarr_name }}-data"

homarr_traefik_enable: true
homarr_traefik_host: "{{ homarr_name }}.{{ common_traefik_domain }}"
homarr_ports:
  - 7575:7575

homarr_secrets: {}

homarr_container_env: {}
homarr_container_secrets: []
homarr_container_labels: {}
homarr_quadlet_options: []
