---
# tasks file for jaredhocutt.homelab.tautulli

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ tautulli_image }}"
      image_tag: "{{ tautulli_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ tautulli_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ tautulli_volume_config }}"
      options: "{{ tautulli_volume_config_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ tautulli_secrets_combined | dict2items }}"

- name: Create tautulli container
  containers.podman.podman_container:
    name: "{{ tautulli_name }}"
    image: "{{ tautulli_image }}:{{ tautulli_image_tag }}"
    network:
      - "{{ tautulli_name }}.network"
      - "{{ tautulli_traefik_enable | ternary(common_traefik_network ~ '.network', omit) }}"
    env: "{{ tautulli_container_env_combined }}"
    secrets: "{{ tautulli_container_secrets_combined }}"
    volumes:
      - "{{ tautulli_volume_config }}:/config"
    publish: "{{ tautulli_traefik_enable | ternary(omit, tautulli_ports) }}"
    labels: "{{ tautulli_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ tautulli_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ tautulli_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
