---
# vars file for jaredhocutt.homelab.radarr

###############################################################################
# Envrionment
###############################################################################

radarr_container_env_base: {}

radarr_container_env_combined: >-
  {{ common_container_env_base
  | combine(radarr_container_env_base, recursive=True)
  | combine(radarr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

radarr_secrets_base: {}

radarr_secrets_combined: >-
  {{ radarr_secrets_base
  | combine(radarr_secrets, recursive=True) }}

radarr_container_secrets_base: []

radarr_container_secrets_combined: >-
  {{ radarr_container_secrets_base
  + radarr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
radarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ radarr_name }}.rule
    value: Host(`{{ radarr_traefik_host }}`)
  - key: traefik.http.routers.{{ radarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ radarr_name }}.loadbalancer.server.port
    value: "7878"
radarr_container_labels_base: "{{ radarr_traefik_enable | ternary((radarr_container_labels_traefik | items2dict), {}) }}"

radarr_container_labels_combined: >-
  {{ radarr_container_labels_base
  | combine(radarr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

radarr_quadlet_options_base: "{{ common_quadlet_options_base }}"

radarr_quadlet_options_combined: >-
  {{ radarr_quadlet_options_base
  + radarr_quadlet_options }}
