---
# vars file for jaredhocutt.homelab.radarr

###############################################################################
# Envrionment Variables
###############################################################################

radarr_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

radarr_secrets_base: {}

radarr_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
radarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ radarr_name }}.rule
    value: Host(`{{ radarr_traefik_host }}`)
  - key: traefik.http.routers.{{ radarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
radarr_container_labels_base: "{{ radarr_traefik_enable | ternary((radarr_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

radarr_quadlet_options_base: "{{ common_quadlet_options_base }}"
