---
# vars file for jaredhocutt.homelab.radarr

###############################################################################
# Envrionment
###############################################################################

radarr_container_env_defaults: {}

radarr_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(radarr_container_env_defaults, recursive=True)
  | combine(radarr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

radarr_secrets_defaults: {}

radarr_secrets_combined: >-
  {{ radarr_secrets_defaults
  | combine(radarr_secrets, recursive=True) }}

radarr_container_secrets_defaults: []

radarr_container_secrets_combined: >-
  {{ radarr_container_secrets_defaults
  + radarr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

radarr_container_labels_defaults: >
  {{ radarr_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', radarr_name, radarr_traefik_host, '7878'), {}) }}

radarr_container_labels_combined: >-
  {{ radarr_container_labels_defaults
  | combine(radarr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

radarr_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

radarr_quadlet_options_combined: >-
  {{ radarr_quadlet_options_defaults
  + radarr_quadlet_options }}
