---
# defaults file for jaredhocutt.homelab.portainer

portainer_name: portainer

portainer_image: docker.io/portainer/portainer-ee
portainer_image_tag: lts

portainer_volume_data: "{{ portainer_name }}-data"

portainer_traefik_enable: true
portainer_traefik_host: "{{ portainer_name }}.{{ common_traefik_domain }}"
portainer_ports:
  - 9443:9443

portainer_env_vars: {}

portainer_secrets: {}
portainer_container_secrets: []

portainer_container_labels: {}

portainer_quadlet_options: []
