---
# tasks file for jaredhocutt.homelab.warracker

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ warracker_image }}"
      image_tag: "{{ warracker_image_tag }}"
    - image: "{{ warracker_postgres_image }}"
      image_tag: "{{ warracker_postgres_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ warracker_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ warracker_volume_uploads }}"
      options: "{{ warracker_volume_uploads_options | default(omit) }}"
    - name: "{{ warracker_postgres_volume_data }}"
      options: "{{ warracker_postgres_volume_data_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ warracker_secrets_combined | dict2items }}"

- name: Create postgres container
  containers.podman.podman_container:
    name: "{{ warracker_name }}-postgres"
    image: "{{ warracker_postgres_image }}:{{ warracker_postgres_image_tag }}"
    network: "{{ warracker_name }}.network"
    env: "{{ warracker_postgres_container_env_combined }}"
    secrets: "{{ warracker_postgres_container_secrets_combined }}"
    volumes:
      - "{{ warracker_postgres_volume_data }}.volume:/var/lib/postgresql/data"
    healthcheck_interval: 30s
    healthcheck_retries: 5
    healthcheck_start_period: 20s
    healthcheck_timeout: 5s
    healthcheck: CMD-SHELL pg_isready -d {{ warracker_postgres_db_name }} -U {{ warracker_postgres_user }}
    labels: "{{ warracker_postgres_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ warracker_postgres_quadlet_options_combined }}"
    state: quadlet
  notify: Restart postgres for {{ warracker_name }}
  become: true

- name: Create warracker container
  containers.podman.podman_container:
    name: "{{ warracker_name }}"
    image: "{{ warracker_image }}:{{ warracker_image_tag }}"
    network:
      - "{{ warracker_name }}.network"
      - "{{ warracker_traefik_enable | ternary(common_traefik_network ~ '.network', omit) }}"
    env: "{{ warracker_container_env_combined }}"
    secrets: "{{ warracker_container_secrets_combined }}"
    volumes:
      - "{{ warracker_volume_uploads }}.volume:/data/uploads"
    publish: "{{ warracker_traefik_enable | ternary(omit, warracker_ports) }}"
    labels: "{{ warracker_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ warracker_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ warracker_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
