---
# vars file for jaredhocutt.homelab.stirling_pdf

###############################################################################
# Envrionment
###############################################################################

stirling_pdf_container_env_base: {}

stirling_pdf_container_env_combined: >-
  {{ common_container_env_base
  | combine(stirling_pdf_container_env_base, recursive=True)
  | combine(stirling_pdf_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

stirling_pdf_secrets_base: {}

stirling_pdf_secrets_combined: >-
  {{ stirling_pdf_secrets_base
  | combine(stirling_pdf_secrets, recursive=True) }}

stirling_pdf_container_secrets_base: []

stirling_pdf_container_secrets_combined: >-
  {{ stirling_pdf_container_secrets_base
  + stirling_pdf_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
stirling_pdf_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ stirling_pdf_name }}.rule
    value: Host(`{{ stirling_pdf_traefik_host }}`)
  - key: traefik.http.routers.{{ stirling_pdf_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
stirling_pdf_container_labels_base: "{{ stirling_pdf_traefik_enable | ternary((stirling_pdf_container_labels_traefik | items2dict), {}) }}"

stirling_pdf_container_labels_combined: >-
  {{ stirling_pdf_container_labels_base
  | combine(stirling_pdf_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

stirling_pdf_quadlet_options_base: "{{ common_quadlet_options_base }}"

stirling_pdf_quadlet_options_combined: >-
  {{ stirling_pdf_quadlet_options_base
  + stirling_pdf_quadlet_options }}
