---
# vars file for jaredhocutt.homelab.stirling_pdf

###############################################################################
# Envrionment
###############################################################################

stirling_pdf_container_env_defaults: {}

stirling_pdf_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(stirling_pdf_container_env_defaults, recursive=True)
  | combine(stirling_pdf_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

stirling_pdf_secrets_defaults: {}

stirling_pdf_secrets_combined: >-
  {{ stirling_pdf_secrets_defaults
  | combine(stirling_pdf_secrets, recursive=True) }}

stirling_pdf_container_secrets_defaults: []

stirling_pdf_container_secrets_combined: >-
  {{ stirling_pdf_container_secrets_defaults
  + stirling_pdf_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

stirling_pdf_container_labels_defaults: >
  {{ stirling_pdf_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', stirling_pdf_name, stirling_pdf_traefik_host, '8080'), {}) }}

stirling_pdf_container_labels_combined: >-
  {{ stirling_pdf_container_labels_defaults
  | combine(stirling_pdf_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

stirling_pdf_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

stirling_pdf_quadlet_options_combined: >-
  {{ stirling_pdf_quadlet_options_defaults
  + stirling_pdf_quadlet_options }}
