---
# vars file for jaredhocutt.homelab.stirling_pdf

###############################################################################
# Envrionment Variables
###############################################################################

stirling_pdf_env_vars_base: "{{ common_env_vars_base }}"

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
stirling_pdf_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ stirling_pdf_name }}.rule
    value: Host(`{{ stirling_pdf_traefik_host }}`)
  - key: traefik.http.routers.{{ stirling_pdf_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
stirling_pdf_container_labels_base: "{{ stirling_pdf_traefik_enable | ternary((stirling_pdf_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

stirling_pdf_quadlet_options_base: "{{ common_quadlet_options_base }}"
