---
# handlers file for jaredhocutt.homelab.shelfmark

- name: Restart {{ shelfmark_name }}
  ansible.builtin.systemd:
    name: "{{ shelfmark_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
