---
# handlers file for jaredhocutt.homelab.bar_assistant

- name: Restart {{ bar_assistant_name }}
  ansible.builtin.systemd:
    name: "{{ bar_assistant_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart salt_rim for {{ bar_assistant_name }}
  ansible.builtin.systemd:
    name: "{{ bar_assistant_name }}-salt-rim.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart redis for {{ bar_assistant_name }}
  ansible.builtin.systemd:
    name: "{{ bar_assistant_name }}-redis.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart meilisearch for {{ bar_assistant_name }}
  ansible.builtin.systemd:
    name: "{{ bar_assistant_name }}-meilisearch.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
