---
# defaults file for jaredhocutt.homelab.authentik

authentik_name: authentik

authentik_image: ghcr.io/goauthentik/server
authentik_image_tag: "2025.8"
authentik_postgres_image: docker.io/library/postgres
authentik_postgres_image_tag: "16"

authentik_volume_media: "{{ authentik_name }}-media"
authentik_volume_certs: "{{ authentik_name }}-certs"
authentik_volume_templates: "{{ authentik_name }}-templates"
authentik_postgres_volume_data: "{{ authentik_name }}-postgres-data"

authentik_traefik_enable: true
authentik_traefik_host: "{{ authentik_name }}.{{ common_traefik_domain }}"
authentik_ports:
  - 9000:9000
  - 9443:9443

authentik_secrets: {}

authentik_container_env: {}
authentik_container_secrets: []
authentik_container_labels: {}
authentik_quadlet_options: []

authentik_worker_container_secrets: []
authentik_worker_container_labels: {}

authentik_postgres_container_env: {}
authentik_postgres_container_secrets: []
authentik_postgres_container_labels: {}
authentik_postgres_quadlet_options: []
