---
# tasks file for jaredhocutt.homelab.wizarr

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ wizarr_image }}"
      image_tag: "{{ wizarr_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ wizarr_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ wizarr_volume_data }}"
      options: "{{ wizarr_volume_data_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ wizarr_secrets_combined | dict2items }}"

- name: Create wizarr container
  containers.podman.podman_container:
    name: "{{ wizarr_name }}"
    image: "{{ wizarr_image }}:{{ wizarr_image_tag }}"
    network: "{{ wizarr_name }}.network"
    env: "{{ wizarr_container_env_combined }}"
    secrets: "{{ wizarr_container_secrets_combined }}"
    volumes:
      - "{{ wizarr_volume_data }}://data"
    publish: "{{ wizarr_traefik_enable | ternary(omit, wizarr_ports) }}"
    labels: "{{ wizarr_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ wizarr_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ wizarr_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
