---
# vars file for jaredhocutt.homelab.sonarr

###############################################################################
# Envrionment Variables
###############################################################################

sonarr_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

sonarr_secrets_base: {}

sonarr_secrets_combined: >-
  {{ sonarr_secrets_base
  | combine(sonarr_secrets, recursive=True) }}

sonarr_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
sonarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ sonarr_name }}.rule
    value: Host(`{{ sonarr_traefik_host }}`)
  - key: traefik.http.routers.{{ sonarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
sonarr_container_labels_base: "{{ sonarr_traefik_enable | ternary((sonarr_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

sonarr_quadlet_options_base: "{{ common_quadlet_options_base }}"
