---
# vars file for jaredhocutt.homelab.sonarr

###############################################################################
# Envrionment
###############################################################################

sonarr_container_env_defaults: {}

sonarr_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(sonarr_container_env_defaults, recursive=True)
  | combine(sonarr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

sonarr_secrets_defaults: {}

sonarr_secrets_combined: >-
  {{ sonarr_secrets_defaults
  | combine(sonarr_secrets, recursive=True) }}

sonarr_container_secrets_defaults: []

sonarr_container_secrets_combined: >-
  {{ sonarr_container_secrets_defaults
  + sonarr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

sonarr_container_labels_defaults: >
  {{ sonarr_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', sonarr_name, sonarr_traefik_host, '8989'), {}) }}

sonarr_container_labels_combined: >-
  {{ sonarr_container_labels_defaults
  | combine(sonarr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

sonarr_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

sonarr_quadlet_options_combined: >-
  {{ sonarr_quadlet_options_defaults
  + sonarr_quadlet_options }}
