---
# vars file for jaredhocutt.homelab.wizarr

###############################################################################
# Envrionment
###############################################################################

wizarr_container_env_defaults: {}

wizarr_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(wizarr_container_env_defaults, recursive=True)
  | combine(wizarr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

wizarr_secrets_defaults: {}

wizarr_secrets_combined: >-
  {{ wizarr_secrets_defaults
  | combine(wizarr_secrets, recursive=True) }}

wizarr_container_secrets_defaults: []

wizarr_container_secrets_combined: >-
  {{ wizarr_container_secrets_defaults
  + wizarr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
wizarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ wizarr_name }}.rule
    value: Host(`{{ wizarr_traefik_host }}`)
  - key: traefik.http.routers.{{ wizarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ wizarr_name }}.loadbalancer.server.port
    value: "5690"
wizarr_container_labels_defaults: "{{ wizarr_traefik_enable | ternary((wizarr_container_labels_traefik | items2dict), {}) }}"

wizarr_container_labels_combined: >-
  {{ wizarr_container_labels_defaults
  | combine(wizarr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

wizarr_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

wizarr_quadlet_options_combined: >-
  {{ wizarr_quadlet_options_defaults
  + wizarr_quadlet_options }}
