---
# vars file for jaredhocutt.homelab.wizarr

wizarr_env_vars_base:
  TZ: "America/New_York"

wizarr_quadlet_options_base:
  - |
    [Service]
    Restart=always
  - |
    [Install]
    WantedBy=multi-user.target
