---
# defaults file for jaredhocutt.homelab.traefik

traefik_name: traefik

traefik_image: docker.io/library/traefik
traefik_image_tag: latest

traefik_volume_certs: "{{ traefik_name }}-certs"
traefik_volume_dynamic: "{{ common_traefik_volume_dynamic }}"

traefik_traefik_enable: true
traefik_traefik_host: "{{ traefik_name }}.{{ common_traefik_domain }}"
traefik_ports:
  - 80:80
  - 443:443

traefik_command: []

traefik_env_vars: {}

traefik_secrets: {}
traefik_container_secrets: []

traefik_container_labels: {}
traefik_quadlet_options: []
