---
# defaults file for jaredhocutt.homelab.traefik

traefik_name: traefik

traefik_image: docker.io/library/traefik
traefik_image_tag: latest

traefik_volume_certs: "{{ traefik_name }}-config"
traefik_volume_dynamic: "{{ traefik_name }}-dynamic"

traefik_ports:
  - 80:80
  - 443:443
  - 8080:8080

traefik_env_vars: {}
traefik_container_labels: {}
traefik_quadlet_options: []
