---
# defaults file for jaredhocutt.homelab.open_webui

open_webui_name: open-webui

open_webui_image: ghcr.io/open-webui/open-webui
open_webui_image_tag: main

open_webui_volume_data: "{{ open_webui_name }}-data"

open_webui_traefik_enable: true
open_webui_traefik_host: "{{ open_webui_name }}.{{ common_traefik_domain }}"
open_webui_ports:
  - 3000:8080

open_webui_secrets: {}

open_webui_container_env: {}
open_webui_container_secrets: []
open_webui_container_labels: {}
open_webui_quadlet_options: []
