---
# defaults file for jaredhocutt.homelab.sonarr

sonarr_name: sonarr

sonarr_image: lscr.io/linuxserver/sonarr
sonarr_image_tag: latest

sonarr_volume_config: "{{ sonarr_name }}-config"
sonarr_volume_download: "{{ sonarr_name }}-download"
sonarr_volume_media: "{{ sonarr_name }}-media"

sonarr_traefik_enable: true
sonarr_traefik_host: "{{ sonarr_name }}.{{ common_traefik_domain }}"
sonarr_ports:
  - 8989:8989

sonarr_secrets: {}

sonarr_env_vars: {}
sonarr_container_secrets: []
sonarr_container_labels: {}
sonarr_quadlet_options: []
