---
# tasks file for jaredhocutt.homelab.karakeep

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ karakeep_image }}"
      image_tag: "{{ karakeep_image_tag }}"
    - image: "{{ karakeep_chrome_image }}"
      image_tag: "{{ karakeep_chrome_image_tag }}"
    - image: "{{ karakeep_meilisearch_image }}"
      image_tag: "{{ karakeep_meilisearch_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ karakeep_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ karakeep_volume_data }}"
      options: "{{ karakeep_volume_data_options | default(omit) }}"
    - name: "{{ karakeep_meilisearch_volume_data }}"
      options: "{{ karakeep_meilisearch_volume_data_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ karakeep_secrets_combined | dict2items }}"

- name: Create chrome container
  containers.podman.podman_container:
    name: "{{ karakeep_name }}-chrome"
    image: "{{ karakeep_chrome_image }}:{{ karakeep_chrome_image_tag }}"
    network: "{{ karakeep_name }}.network"
    env: "{{ karakeep_chrome_container_env_combined }}"
    secrets: "{{ karakeep_chrome_container_secrets_combined }}"
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    labels: "{{ karakeep_chrome_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ karakeep_chrome_quadlet_options_combined }}"
    state: quadlet
  notify: Restart chrome for {{ karakeep_name }}
  become: true

- name: Create meilisearch container
  containers.podman.podman_container:
    name: "{{ karakeep_name }}-meilisearch"
    image: "{{ karakeep_meilisearch_image }}:{{ karakeep_meilisearch_image_tag }}"
    network: "{{ karakeep_name }}.network"
    env: "{{ karakeep_meilisearch_container_env_combined }}"
    secrets: "{{ karakeep_meilisearch_container_secrets_combined }}"
    volumes:
      - "{{ karakeep_meilisearch_volume_data }}.volume:/meili_data"
    labels: "{{ karakeep_meilisearch_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ karakeep_meilisearch_quadlet_options_combined }}"
    state: quadlet
  notify: Restart meilisearch for {{ karakeep_name }}
  become: true

- name: Create karakeep container
  containers.podman.podman_container:
    name: "{{ karakeep_name }}"
    image: "{{ karakeep_image }}:{{ karakeep_image_tag }}"
    network:
      - "{{ karakeep_name }}.network"
      - "{{ karakeep_traefik_enable | ternary(common_traefik_network ~ '.network', omit) }}"
    env: "{{ karakeep_container_env_combined }}"
    secrets: "{{ karakeep_container_secrets_combined }}"
    volumes:
      - "{{ karakeep_volume_data }}.volume:/data"
    publish: "{{ karakeep_traefik_enable | ternary(omit, karakeep_ports) }}"
    labels: "{{ karakeep_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ karakeep_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ karakeep_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
