---

- name: Stop services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  become: true
  failed_when: false
  loop:
    - "{{ nocodb_name }}.service"
    - "{{ nocodb_name }}-postgres.service"

- name: Destroy containers
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ nocodb_name }}"
    - "{{ nocodb_name }}-postgres"

- name: Destroy secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    state: absent
  become: true
  no_log: true
  loop: "{{ nocodb_secrets_base | combine(nocodb_secrets, recursive=True) | dict2items }}"

- name: Destroy volumes
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ nocodb_volume_data }}"
    - "{{ nocodb_postgres_volume_data }}"

- name: Destroy network
  containers.podman.podman_network:
    name: "{{ nocodb_name }}"
    state: absent
  become: true

- name: Cleanup quadlet files
  ansible.builtin.file:
    path: /etc/containers/systemd/{{ item }}
    state: absent
  become: true
  loop:
    - "{{ nocodb_name }}.container"
    - "{{ nocodb_name }}-postgres.container"
    - "{{ nocodb_volume_data }}.volume"
    - "{{ nocodb_postgres_volume_data }}.volume"
    - "{{ nocodb_name }}.network"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
