---
# vars file for jaredhocutt.homelab.open_webui

###############################################################################
# Envrionment
###############################################################################

open_webui_container_env_defaults: {}

open_webui_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(open_webui_container_env_defaults, recursive=True)
  | combine(open_webui_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

open_webui_secrets_defaults: {}

open_webui_secrets_combined: >-
  {{ open_webui_secrets_defaults
  | combine(open_webui_secrets, recursive=True) }}

open_webui_container_secrets_defaults: []

open_webui_container_secrets_combined: >-
  {{ open_webui_container_secrets_defaults
  + open_webui_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
open_webui_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ open_webui_name }}.rule
    value: Host(`{{ open_webui_traefik_host }}`)
  - key: traefik.http.routers.{{ open_webui_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ open_webui_name }}.loadbalancer.server.port
    value: "8080"
open_webui_container_labels_defaults: "{{ open_webui_traefik_enable | ternary((open_webui_container_labels_traefik | items2dict), {}) }}"

open_webui_container_labels_combined: >-
  {{ open_webui_container_labels_defaults
  | combine(open_webui_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

open_webui_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

open_webui_quadlet_options_combined: >-
  {{ open_webui_quadlet_options_defaults
  + open_webui_quadlet_options }}
