---
# defaults file for jaredhocutt.homelab.bar_assistant

bar_assistant_name: bar-assistant

bar_assistant_image: docker.io/barassistant/server
bar_assistant_image_tag: dev
bar_assistant_salt_rim_image: docker.io/barassistant/salt-rim
bar_assistant_salt_rim_image_tag: dev
bar_assistant_redis_image: docker.io/library/redis
bar_assistant_redis_image_tag: latest
bar_assistant_meilisearch_image: docker.io/getmeili/meilisearch
bar_assistant_meilisearch_image_tag: latest

bar_assistant_volume_data: "{{ bar_assistant_name }}-data"
bar_assistant_redis_volume_data: "{{ bar_assistant_name }}-redis-data"
bar_assistant_meilisearch_volume_data: "{{ bar_assistant_name }}-meilisearch-data"

bar_assistant_traefik_enable: true
bar_assistant_traefik_host: "{{ bar_assistant_name }}-api.{{ common_traefik_domain }}"
bar_assistant_salt_rim_traefik_host: "{{ bar_assistant_name }}.{{ common_traefik_domain }}"
bar_assistant_meilisearch_traefik_host: "{{ bar_assistant_name }}-meilisearch.{{ common_traefik_domain }}"
bar_assistant_ports:
  - 8082:8080
bar_assistant_salt_rim_ports:
  - 8080:8080
bar_assistant_meilisearch_ports:
  - 8081:7700

bar_assistant_secrets: {}

bar_assistant_env_vars: {}
bar_assistant_container_secrets: []
bar_assistant_container_labels: {}
bar_assistant_quadlet_options: []

bar_assistant_salt_rim_env_vars: {}
bar_assistant_salt_rim_container_secrets: []
bar_assistant_salt_rim_container_labels: {}
bar_assistant_salt_rim_quadlet_options: []

bar_assistant_redis_env_vars: {}
bar_assistant_redis_container_secrets: []
bar_assistant_redis_container_labels: {}
bar_assistant_redis_quadlet_options: []

bar_assistant_meilisearch_env_vars: {}
bar_assistant_meilisearch_container_secrets: []
bar_assistant_meilisearch_container_labels: {}
bar_assistant_meilisearch_quadlet_options: []

bar_assistant_api_url: https://{{ bar_assistant_traefik_host }}
bar_assistant_meilisearch_url: https://{{ bar_assistant_meilisearch_traefik_host }}
