---
# vars file for jaredhocutt.homelab.prowlarr

###############################################################################
# Envrionment
###############################################################################

prowlarr_container_env_defaults: {}

prowlarr_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(prowlarr_container_env_defaults, recursive=True)
  | combine(prowlarr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

prowlarr_secrets_defaults: {}

prowlarr_secrets_combined: >-
  {{ prowlarr_secrets_defaults
  | combine(prowlarr_secrets, recursive=True) }}

prowlarr_container_secrets_defaults: []

prowlarr_container_secrets_combined: >-
  {{ prowlarr_container_secrets_defaults
  + prowlarr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
prowlarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ prowlarr_name }}.rule
    value: Host(`{{ prowlarr_traefik_host }}`)
  - key: traefik.http.routers.{{ prowlarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ prowlarr_name }}.loadbalancer.server.port
    value: "9696"
prowlarr_container_labels_defaults: "{{ prowlarr_traefik_enable | ternary((prowlarr_container_labels_traefik | items2dict), {}) }}"

prowlarr_container_labels_combined: >-
  {{ prowlarr_container_labels_defaults
  | combine(prowlarr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

prowlarr_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

prowlarr_quadlet_options_combined: >-
  {{ prowlarr_quadlet_options_defaults
  + prowlarr_quadlet_options }}
