---
# handlers file for jaredhocutt.homelab.bentopdf

- name: Restart {{ bentopdf_name }}
  ansible.builtin.systemd:
    name: "{{ bentopdf_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
