---
# vars file for jaredhocutt.homelab.overseerr

###############################################################################
# Envrionment Variables
###############################################################################

overseerr_env_vars_base: "{{ common_env_vars_base }}"

###############################################################################
# Container Labels
###############################################################################

overseerr_container_labels_traefik:
  traefik.enable: true
  traefik.http.routers.{{ overseerr_name }}.rule: Host(`{{ overseerr_traefik_host }}`)
  traefik.http.routers.{{ overseerr_name }}.entrypoints: "{{ common_traefik_entrypoint }}"
overseerr_container_labels_base: "{{ overseerr_traefik_enable | ternary(overseerr_container_labels_traefik, {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

overseerr_quadlet_options_base: "{{ common_quadlet_options_base }}"
