---
# vars file for jaredhocutt.homelab.overseerr

###############################################################################
# Envrionment
###############################################################################

overseerr_container_env_base: {}

overseerr_container_env_combined: >-
  {{ common_container_env_base
  | combine(overseerr_container_env_base, recursive=True)
  | combine(overseerr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

overseerr_secrets_base: {}

overseerr_secrets_combined: >-
  {{ overseerr_secrets_base
  | combine(overseerr_secrets, recursive=True) }}

overseerr_container_secrets_base: []

overseerr_container_secrets_combined: >-
  {{ overseerr_container_secrets_base
  + overseerr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
overseerr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ overseerr_name }}.rule
    value: Host(`{{ overseerr_traefik_host }}`)
  - key: traefik.http.routers.{{ overseerr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ overseerr_name }}.loadbalancer.server.port
    value: "5055"
overseerr_container_labels_base: "{{ overseerr_traefik_enable | ternary((overseerr_container_labels_traefik | items2dict), {}) }}"

overseerr_container_labels_combined: >-
  {{ overseerr_container_labels_base
  | combine(overseerr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

overseerr_quadlet_options_base: "{{ common_quadlet_options_base }}"

overseerr_quadlet_options_combined: >-
  {{ overseerr_quadlet_options_base
  + overseerr_quadlet_options }}
