---
# vars file for jaredhocutt.homelab.common

###############################################################################
# Envrionment
###############################################################################

common_container_env_base:
  TZ: "America/New_York"

###############################################################################
# Quadlet Options
###############################################################################

common_quadlet_options_base:
  - |
    [Service]
    Restart=always
  - |
    [Install]
    WantedBy=multi-user.target
