---
# defaults file for jaredhocutt.homelab.healthchecks

healthchecks_name: healthchecks

healthchecks_image: lscr.io/linuxserver/healthchecks
healthchecks_image_tag: latest

healthchecks_volume_config: "{{ healthchecks_name }}-config"

healthchecks_traefik_enable: true
healthchecks_traefik_host: "{{ healthchecks_name }}.{{ common_traefik_domain }}"
healthchecks_ports:
  - 8000:8000

healthchecks_secrets: {}

healthchecks_container_env: {}
healthchecks_container_secrets: []
healthchecks_container_labels: {}
healthchecks_quadlet_options: []

healthchecks_site_name: Healthchecks
healthchecks_url: https://{{ healthchecks_traefik_host }}
