---
# vars file for jaredhocutt.homelab.uptime_kuma

###############################################################################
# Envrionment Variables
###############################################################################

uptime_kuma_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

uptime_kuma_secrets_base: {}

uptime_kuma_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
uptime_kuma_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ uptime_kuma_name }}.rule
    value: Host(`{{ uptime_kuma_traefik_host }}`)
  - key: traefik.http.routers.{{ uptime_kuma_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
uptime_kuma_container_labels_base: "{{ uptime_kuma_traefik_enable | ternary((uptime_kuma_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

uptime_kuma_quadlet_options_base: "{{ common_quadlet_options_base }}"
