---
# tasks file for jaredhocutt.homelab.prowlarr

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ prowlarr_image }}"
      image_tag: "{{ prowlarr_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ prowlarr_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ prowlarr_volume_config }}"
      options: "{{ prowlarr_volume_config_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ prowlarr_secrets_combined | dict2items }}"

- name: Create prowlarr container
  containers.podman.podman_container:
    name: "{{ prowlarr_name }}"
    image: "{{ prowlarr_image }}:{{ prowlarr_image_tag }}"
    network: "{{ prowlarr_name }}.network"
    env: >-
      {{ common_env_vars_base
      | combine(prowlarr_env_vars_base, recursive=True)
      | combine(prowlarr_env_vars, recursive=True) }}
    secrets: >-
      {{ prowlarr_container_secrets_base
      + prowlarr_container_secrets }}
    volumes:
      - "{{ prowlarr_volume_config }}:/config"
    publish: "{{ prowlarr_traefik_enable | ternary(omit, prowlarr_ports) }}"
    labels: "{{ prowlarr_container_labels_base | combine(prowlarr_container_labels, recursive=True) }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ prowlarr_quadlet_options_base + prowlarr_quadlet_options }}"
    state: quadlet
  notify: Restart {{ prowlarr_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
