---
# tasks file for jaredhocutt.homelab.portainer

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ portainer_image }}"
      image_tag: "{{ portainer_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ portainer_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ portainer_volume_data }}"
      options: "{{ portainer_volume_data_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ portainer_secrets_base | combine(portainer_secrets, recursive=True) | dict2items }}"

- name: Create portainer container
  containers.podman.podman_container:
    name: "{{ portainer_name }}"
    image: "{{ portainer_image }}:{{ portainer_image_tag }}"
    network: "{{ portainer_name }}.network"
    env: >-
      {{ common_env_vars_base
      | combine(portainer_env_vars_base, recursive=True)
      | combine(portainer_env_vars, recursive=True) }}
    secrets: >-
      {{ portainer_container_secrets_base
      + portainer_container_secrets }}
    volumes:
      - "{{ portainer_volume_config }}:/data"
      - /var/run/podman.sock:/var/run/docker.sock
    publish: "{{ portainer_traefik_enable | ternary(omit, portainer_ports) }}"
    labels: "{{ portainer_container_labels_base | combine(portainer_container_labels, recursive=True) }}"
    privileged: true
    quadlet_file_mode: "0600"
    quadlet_options: "{{ portainer_quadlet_options_base + portainer_quadlet_options }}"
    state: quadlet
  notify: Restart {{ portainer_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
