---
# tasks file for jaredhocutt.homelab.homarr

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ homarr_image }}"
      image_tag: "{{ homarr_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ homarr_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ homarr_volume_data }}"
      options: "{{ homarr_volume_data_options | default(omit) }}"

- name: Create homarr container
  containers.podman.podman_container:
    name: "{{ homarr_name }}"
    image: "{{ homarr_image }}:{{ homarr_image_tag }}"
    network: "{{ homarr_name }}.network"
    env: "{{ homarr_env_vars_base | combine(homarr_env_vars, recursive=True) }}"
    volumes:
      - "{{ homarr_volume_data }}:/appdata"
    publish: "{{ homarr_ports }}"
    labels: "{{ homarr_container_labels | default(omit) }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ homarr_quadlet_options_base + homarr_quadlet_options }}"
    state: quadlet
  notify: Restart {{ homarr_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
