---

- name: Stop services
  ansible.builtin.systemd:
    name: "{{ item}}"
    state: stopped
  become: true
  failed_when: false
  loop:
    - "{{ sonarr_name }}.service"

- name: Destroy containers
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ sonarr_name }}"

- name: Destroy secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    state: absent
  become: true
  no_log: true
  loop: "{{ sonarr_secrets_base | combine(sonarr_secrets, recursive=True) | dict2items }}"

- name: Destroy volumes
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ sonarr_volume_config }}"
    - "{{ sonarr_volume_download }}"
    - "{{ sonarr_volume_media }}"

- name: Destroy network
  containers.podman.podman_network:
    name: "{{ sonarr_name }}"
    state: absent
  become: true

- name: Cleanup quadlet files
  ansible.builtin.file:
    path: /etc/containers/systemd/{{ item }}
    state: absent
  become: true
  loop:
    - "{{ sonarr_name }}.container"
    - "{{ sonarr_volume_config }}.volume"
    - "{{ sonarr_volume_download }}.volume"
    - "{{ sonarr_volume_media }}.volume"
    - "{{ sonarr_name }}.network"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
