---
# tasks file for jaredhocutt.homelab.sonarr

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ sonarr_image }}"
      image_tag: "{{ sonarr_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ sonarr_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ sonarr_volume_config }}"
      options: "{{ sonarr_volume_config_options | default(omit) }}"
    - name: "{{ sonarr_volume_download }}"
      options: "{{ sonarr_volume_download_options | default(omit) }}"
    - name: "{{ sonarr_volume_media }}"
      options: "{{ sonarr_volume_media_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ sonarr_secrets_combined | dict2items }}"

- name: Create sonarr container
  containers.podman.podman_container:
    name: "{{ sonarr_name }}"
    image: "{{ sonarr_image }}:{{ sonarr_image_tag }}"
    network: "{{ sonarr_name }}.network"
    env: "{{ sonarr_container_env_combined }}"
    secrets: "{{ sonarr_container_secrets_combined }}"
    volumes:
      - "{{ sonarr_volume_config }}:/config"
      - "{{ sonarr_volume_download }}:/mnt/download"
      - "{{ sonarr_volume_media }}:/mnt/media"
    publish: "{{ sonarr_traefik_enable | ternary(omit, sonarr_ports) }}"
    labels: "{{ sonarr_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ sonarr_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ sonarr_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
