---
# tasks file for jaredhocutt.homelab.shelfmark

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ shelfmark_image }}"
      image_tag: "{{ shelfmark_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ shelfmark_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ shelfmark_volume_config }}"
      options: "{{ shelfmark_volume_config_options | default(omit) }}"
    - name: "{{ shelfmark_volume_books }}"
      options: "{{ shelfmark_volume_books_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ shelfmark_secrets_combined | dict2items }}"

- name: Create shelfmark container
  containers.podman.podman_container:
    name: "{{ shelfmark_name }}"
    image: "{{ shelfmark_image }}:{{ shelfmark_image_tag }}"
    network:
      - "{{ shelfmark_name }}.network"
      - "{{ shelfmark_traefik_enable | ternary(common_traefik_network ~ '.network', omit) }}"
    env: "{{ shelfmark_container_env_combined }}"
    secrets: "{{ shelfmark_container_secrets_combined }}"
    volumes:
      - "{{ shelfmark_volume_config }}:/config"
      - "{{ shelfmark_volume_books }}:/books"
    publish: "{{ shelfmark_traefik_enable | ternary(omit, shelfmark_ports) }}"
    labels: "{{ shelfmark_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ shelfmark_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ shelfmark_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
