---
# tasks file for jaredhocutt.homelab.kometa

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ kometa_image }}"
      image_tag: "{{ kometa_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ kometa_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ kometa_volume_config }}"
      options: "{{ kometa_volume_config_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ kometa_secrets_combined | dict2items }}"

- name: Create kometa container
  containers.podman.podman_container:
    name: "{{ kometa_name }}"
    image: "{{ kometa_image }}:{{ kometa_image_tag }}"
    network: "{{ kometa_name }}.network"
    env: "{{ kometa_container_env_combined }}"
    secrets: "{{ kometa_container_secrets_combined }}"
    volumes:
      - "{{ kometa_volume_config }}:/config"
    labels: "{{ kometa_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ kometa_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ kometa_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
