---
# defaults file for jaredhocutt.homelab.prowlarr

prowlarr_name: prowlarr

prowlarr_image: lscr.io/linuxserver/prowlarr
prowlarr_image_tag: latest

prowlarr_volume_config: "{{ prowlarr_name }}-config"

prowlarr_traefik_enable: true
prowlarr_traefik_host: "{{ prowlarr_name }}.{{ common_traefik_domain }}"
prowlarr_ports:
  - 9696:9696

prowlarr_env_vars: {}

prowlarr_secrets: {}
prowlarr_container_secrets: []

prowlarr_container_labels: {}

prowlarr_quadlet_options: []
