---
# vars file for jaredhocutt.homelab.portainer

###############################################################################
# Envrionment
###############################################################################

portainer_container_env_defaults: {}

portainer_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(portainer_container_env_defaults, recursive=True)
  | combine(portainer_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

portainer_secrets_defaults: {}

portainer_secrets_combined: >-
  {{ portainer_secrets_defaults
  | combine(portainer_secrets, recursive=True) }}

portainer_container_secrets_defaults: []

portainer_container_secrets_combined: >-
  {{ portainer_container_secrets_defaults
  + portainer_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

portainer_container_labels_defaults: >
  {{ portainer_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', portainer_name, portainer_traefik_host, '9443'), {}) }}

portainer_container_labels_combined: >-
  {{ portainer_container_labels_defaults
  | combine(portainer_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

portainer_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

portainer_quadlet_options_combined: >-
  {{ portainer_quadlet_options_defaults
  + portainer_quadlet_options }}
