---
# vars file for jaredhocutt.homelab.portainer

###############################################################################
# Envrionment Variables
###############################################################################

portainer_env_vars_base: "{{ common_env_vars_base }}"

###############################################################################
# Container Labels
###############################################################################

portainer_container_labels_traefik:
  traefik.enable: true
  traefik.http.routers.{{ portainer_name }}.rule: Host(`{{ portainer_traefik_host }}`)
  traefik.http.routers.{{ portainer_name }}.entrypoints: "{{ common_traefik_entrypoint }}"
portainer_container_labels_base: "{{ portainer_traefik_enable | ternary(portainer_container_labels_traefik, {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

portainer_quadlet_options_base: "{{ common_quadlet_options_base }}"
