---
# tasks file for jaredhocutt.homelab.uptime_kuma

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ uptime_kuma_image }}"
      image_tag: "{{ uptime_kuma_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ uptime_kuma_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ uptime_kuma_volume_data }}"
      options: "{{ uptime_kuma_volume_data_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ uptime_kuma_secrets_combined | dict2items }}"

- name: Create uptime_kuma container
  containers.podman.podman_container:
    name: "{{ uptime_kuma_name }}"
    image: "{{ uptime_kuma_image }}:{{ uptime_kuma_image_tag }}"
    network: "{{ uptime_kuma_name }}.network"
    env: >-
      {{ common_env_vars_base
      | combine(uptime_kuma_env_vars_base, recursive=True)
      | combine(uptime_kuma_env_vars, recursive=True) }}
    secrets: >-
      {{ uptime_kuma_container_secrets_base
      + uptime_kuma_container_secrets }}
    volumes:
      - "{{ uptime_kuma_volume_data }}:/app/data"
    publish: "{{ uptime_kuma_traefik_enable | ternary(omit, uptime_kuma_ports) }}"
    labels: "{{ uptime_kuma_container_labels_base | combine(uptime_kuma_container_labels, recursive=True) }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ uptime_kuma_quadlet_options_base + uptime_kuma_quadlet_options }}"
    state: quadlet
  notify: Restart {{ uptime_kuma_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
