---
# vars file for jaredhocutt.homelab.paperless

paperless_postgres_db_name: paperless
paperless_postgres_user: paperless

###############################################################################
# Envrionment Variables
###############################################################################

paperless_env_vars_base_custom:
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: "{{ paperless_name }}-postgres"
  PAPERLESS_DBNAME: "{{ paperless_postgres_db_name }}"
  PAPERLESS_DBUSER: "{{ paperless_postgres_user }}"
  PAPERLESS_DBPASS: "{{ paperless_postgres_password }}"
  PAPERLESS_REDIS: redis://{{ paperless_name }}-redis:6379
  PAPERLESS_TIKA_ENABLED: 1
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://{{ paperless_name }}-gotenberg:3000
  PAPERLESS_TIKA_ENDPOINT: http://{{ paperless_name }}-tika:9998
  PAPERLESS_URL: "{{ paperless_url }}"
  PAPERLESS_DATE_ORDER: MDY
  PAPERLESS_CONSUMER_POLLING: 30
  PAPERLESS_TASK_WORKERS: "{{ paperless_task_workers }}"
paperless_env_vars_base: "{{ common_env_vars_base | combine(paperless_env_vars_base_custom, recursive=True) }}"

paperless_postgres_env_vars_base_custom:
  POSTGRES_DB: "{{ paperless_postgres_db_name }}"
  POSTGRES_USER: "{{ paperless_postgres_user }}"
  POSTGRES_PASSWORD: "{{ paperless_postgres_password }}"
paperless_postgres_env_vars_base: "{{ common_env_vars_base | combine(paperless_postgres_env_vars_base_custom, recursive=True) }}"

paperless_redis_env_vars_base: "{{ common_env_vars_base }}"

paperless_gotenberg_env_vars_base: "{{ common_env_vars_base }}"

paperless_tika_env_vars_base: "{{ common_env_vars_base }}"

paperless_ai_env_vars_base: "{{ common_env_vars_base }}"

###############################################################################
# Container Labels
###############################################################################

paperless_container_labels_traefik:
  traefik.enable: true
  traefik.http.routers.{{ paperless_name }}.rule: Host(`{{ paperless_traefik_host }}`)
  traefik.http.routers.{{ paperless_name }}.entrypoints: "{{ common_traefik_entrypoint }}"
paperless_container_labels_base: "{{ paperless_traefik_enable | ternary(paperless_container_labels_traefik, {}) }}"

paperless_postgres_container_labels_base: {}

paperless_redis_container_labels_base: {}

paperless_gotenberg_container_labels_base: {}

paperless_tika_container_labels_base: {}

paperless_ai_container_labels_traefik:
  traefik.enable: true
  traefik.http.routers.{{ paperless_name }}.rule: Host(`{{ paperless_ai_traefik_host }}`)
  traefik.http.routers.{{ paperless_name }}.entrypoints: "{{ common_traefik_entrypoint }}"
paperless_ai_container_labels_base: "{{ paperless_traefik_enable | ternary(paperless_ai_container_labels_traefik, {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

paperless_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ paperless_name }}-postgres.service
    Requires={{ paperless_name }}-redis.service
    Requires={{ paperless_name }}-gotenberg.service
    Requires={{ paperless_name }}-tika.service
    After={{ paperless_name }}-postgres.service
    After={{ paperless_name }}-redis.service
    After={{ paperless_name }}-gotenberg.service
    After={{ paperless_name }}-tika.service
paperless_quadlet_options_base: "{{ common_quadlet_options_base + paperless_quadlet_options_base_custom }}"

paperless_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_redis_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_gotenberg_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_tika_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_ai_quadlet_options_base: "{{ common_quadlet_options_base }}"
