---
# vars file for jaredhocutt.homelab.paperless

paperless_postgres_db_name: paperless
paperless_postgres_user: paperless

###############################################################################
# Envrionment Variables
###############################################################################

paperless_env_vars_base:
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: "{{ paperless_name }}-postgres"
  PAPERLESS_REDIS: redis://{{ paperless_name }}-redis:6379
  PAPERLESS_TIKA_ENABLED: 1
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://{{ paperless_name }}-gotenberg:3000
  PAPERLESS_TIKA_ENDPOINT: http://{{ paperless_name }}-tika:9998
  PAPERLESS_URL: "{{ paperless_url }}"
  PAPERLESS_DATE_ORDER: MDY
  PAPERLESS_CONSUMER_POLLING: 30
  PAPERLESS_TASK_WORKERS: "{{ paperless_task_workers }}"

paperless_postgres_env_vars_base: {}

paperless_redis_env_vars_base: {}

paperless_gotenberg_env_vars_base: {}

paperless_tika_env_vars_base: {}

paperless_ai_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

paperless_secrets_base:
  paperless_postgres_db_name: "{{ paperless_postgres_db_name }}"
  paperless_postgres_user: "{{ paperless_postgres_user }}"
  paperless_postgres_password: "{{ paperless_postgres_password }}"

paperless_container_secrets_base:
  - paperless_postgres_db_name,type=env,target=PAPERLESS_DBNAME
  - paperless_postgres_user,type=env,target=PAPERLESS_DBUSER
  - paperless_postgres_password,type=env,target=PAPERLESS_DBPASS

paperless_postgres_container_secrets_base:
  - paperless_postgres_db_name,type=env,target=POSTGRES_DB
  - paperless_postgres_user,type=env,target=POSTGRES_USER
  - paperless_postgres_password,type=env,target=POSTGRES_PASSWORD

paperless_redis_container_secrets_base: []

paperless_gotenberg_container_secrets_base: []

paperless_tika_container_secrets_base: []

paperless_ai_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
paperless_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ paperless_name }}.rule
    value: Host(`{{ paperless_traefik_host }}`)
  - key: traefik.http.routers.{{ paperless_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
paperless_container_labels_base: "{{ paperless_traefik_enable | ternary((paperless_container_labels_traefik | items2dict), {}) }}"

paperless_postgres_container_labels_base: {}

paperless_redis_container_labels_base: {}

paperless_gotenberg_container_labels_base: {}

paperless_tika_container_labels_base: {}

# This is done as a list and converted to a dict in order to use variables in the key name
paperless_ai_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ paperless_name }}-ai.rule
    value: Host(`{{ paperless_ai_traefik_host }}`)
  - key: traefik.http.routers.{{ paperless_name }}-ai.entrypoints
    value: "{{ common_traefik_entrypoint }}"
paperless_ai_container_labels_base: "{{ paperless_traefik_enable | ternary((paperless_ai_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

paperless_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ paperless_name }}-postgres.service
    Requires={{ paperless_name }}-redis.service
    Requires={{ paperless_name }}-gotenberg.service
    Requires={{ paperless_name }}-tika.service
    After={{ paperless_name }}-postgres.service
    After={{ paperless_name }}-redis.service
    After={{ paperless_name }}-gotenberg.service
    After={{ paperless_name }}-tika.service
paperless_quadlet_options_base: "{{ common_quadlet_options_base + paperless_quadlet_options_base_custom }}"

paperless_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_redis_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_gotenberg_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_tika_quadlet_options_base: "{{ common_quadlet_options_base }}"

paperless_ai_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ paperless_name }}.service
    After={{ paperless_name }}.service
paperless_ai_quadlet_options_base: "{{ common_quadlet_options_base + paperless_ai_quadlet_options_base_custom }}"
