---
# vars file for jaredhocutt.homelab.tandoor

tandoor_postgres_db_name: tandoor
tandoor_postgres_user: tandoor

###############################################################################
# Envrionment Variables
###############################################################################

tandoor_env_vars_base:
  DB_ENGINE: django.db.backends.postgresql
  POSTGRES_HOST: "{{ tandoor_name }}-postgres"
  POSTGRES_PORT: "5432"

tandoor_postgres_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

tandoor_secrets_base:
  tandoor_secret_key: "{{ tandoor_secret_key }}"
  tandoor_postgres_db_name: "{{ tandoor_postgres_db_name }}"
  tandoor_postgres_user: "{{ tandoor_postgres_user }}"
  tandoor_postgres_password: "{{ tandoor_postgres_password }}"

tandoor_secrets_combined: >-
  {{ tandoor_secrets_base
  | combine(tandoor_secrets, recursive=True) }}

tandoor_container_secrets_base:
  - tandoor_secret_key,type=env,target=SECRET_KEY
  - tandoor_postgres_db_name,type=env,target=POSTGRES_DB
  - tandoor_postgres_user,type=env,target=POSTGRES_USER
  - tandoor_postgres_password,type=env,target=POSTGRES_PASSWORD

tandoor_postgres_container_secrets_base:
  - tandoor_postgres_db_name,type=env,target=POSTGRES_DB
  - tandoor_postgres_user,type=env,target=POSTGRES_USER
  - tandoor_postgres_password,type=env,target=POSTGRES_PASSWORD

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
tandoor_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ tandoor_name }}.rule
    value: Host(`{{ tandoor_traefik_host }}`)
  - key: traefik.http.routers.{{ tandoor_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
tandoor_container_labels_base: "{{ tandoor_traefik_enable | ternary((tandoor_container_labels_traefik | items2dict), {}) }}"

tandoor_postgres_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

tandoor_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ tandoor_name }}-postgres.service
    After={{ tandoor_name }}-postgres.service
tandoor_quadlet_options_base: "{{ common_quadlet_options_base + tandoor_quadlet_options_base_custom }}"

tandoor_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"
