---
# vars file for jaredhocutt.homelab.tandoor

tandoor_postgres_db_name: tandoor
tandoor_postgres_user: tandoor

###############################################################################
# Envrionment
###############################################################################

tandoor_container_env_defaults:
  DB_ENGINE: django.db.backends.postgresql
  POSTGRES_HOST: "{{ tandoor_name }}-postgres"
  POSTGRES_PORT: "5432"

tandoor_postgres_container_env_defaults: {}

tandoor_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(tandoor_container_env_defaults, recursive=True)
  | combine(tandoor_container_env, recursive=True) }}
tandoor_postgres_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(tandoor_postgres_container_env_defaults, recursive=True)
  | combine(tandoor_postgres_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

tandoor_secrets_defaults:
  tandoor_secret_key: "{{ tandoor_secret_key }}"
  tandoor_postgres_db_name: "{{ tandoor_postgres_db_name }}"
  tandoor_postgres_user: "{{ tandoor_postgres_user }}"
  tandoor_postgres_password: "{{ tandoor_postgres_password }}"

tandoor_secrets_combined: >-
  {{ tandoor_secrets_defaults
  | combine(tandoor_secrets, recursive=True) }}

tandoor_container_secrets_defaults:
  - tandoor_secret_key,type=env,target=SECRET_KEY
  - tandoor_postgres_db_name,type=env,target=POSTGRES_DB
  - tandoor_postgres_user,type=env,target=POSTGRES_USER
  - tandoor_postgres_password,type=env,target=POSTGRES_PASSWORD

tandoor_postgres_container_secrets_defaults:
  - tandoor_postgres_db_name,type=env,target=POSTGRES_DB
  - tandoor_postgres_user,type=env,target=POSTGRES_USER
  - tandoor_postgres_password,type=env,target=POSTGRES_PASSWORD

tandoor_container_secrets_combined: >-
  {{ tandoor_container_secrets_defaults
  + tandoor_container_secrets }}
tandoor_postgres_container_secrets_combined: >-
  {{ tandoor_postgres_container_secrets_defaults
  + tandoor_postgres_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

tandoor_container_labels_defaults: >
  {{ tandoor_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', tandoor_name, tandoor_traefik_host, '80'), {}) }}

tandoor_postgres_container_labels_defaults: {}

tandoor_container_labels_combined: >-
  {{ tandoor_container_labels_defaults
  | combine(tandoor_container_labels, recursive=True) }}
tandoor_postgres_container_labels_combined: >-
  {{ tandoor_postgres_container_labels_defaults
  | combine(tandoor_postgres_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

tandoor_quadlet_options_depends:
  - |
    [Unit]
    Requires={{ tandoor_name }}-postgres.service
    After={{ tandoor_name }}-postgres.service
tandoor_quadlet_options_defaults: "{{ common_quadlet_options_defaults + tandoor_quadlet_options_depends }}"

tandoor_postgres_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

tandoor_quadlet_options_combined: >-
  {{ tandoor_quadlet_options_defaults
  + tandoor_quadlet_options }}
tandoor_postgres_quadlet_options_combined: >-
  {{ tandoor_postgres_quadlet_options_defaults
  + tandoor_postgres_quadlet_options }}
