---
# vars file for jaredhocutt.homelab.bentopdf

###############################################################################
# Envrionment
###############################################################################

bentopdf_container_env_defaults: {}

bentopdf_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(bentopdf_container_env_defaults, recursive=True)
  | combine(bentopdf_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

bentopdf_secrets_defaults: {}

bentopdf_secrets_combined: >-
  {{ bentopdf_secrets_defaults
  | combine(bentopdf_secrets, recursive=True) }}

bentopdf_container_secrets_defaults: []

bentopdf_container_secrets_combined: >-
  {{ bentopdf_container_secrets_defaults
  + bentopdf_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
bentopdf_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ bentopdf_name }}.rule
    value: Host(`{{ bentopdf_traefik_host }}`)
  - key: traefik.http.routers.{{ bentopdf_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ bentopdf_name }}.loadbalancer.server.port
    value: "8080"
bentopdf_container_labels_defaults: "{{ bentopdf_traefik_enable | ternary((bentopdf_container_labels_traefik | items2dict), {}) }}"

bentopdf_container_labels_combined: >-
  {{ bentopdf_container_labels_defaults
  | combine(bentopdf_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

bentopdf_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

bentopdf_quadlet_options_combined: >-
  {{ bentopdf_quadlet_options_defaults
  + bentopdf_quadlet_options }}
