---
# tasks file for jaredhocutt.homelab.overseerr

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ overseerr_image }}"
      image_tag: "{{ overseerr_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ overseerr_name }}"
    driver: bridge
    disable_dns: false
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ overseerr_volume_config }}"
      options: "{{ overseerr_volume_config_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ overseerr_secrets_combined | dict2items }}"

- name: Create overseerr container
  containers.podman.podman_container:
    name: "{{ overseerr_name }}"
    image: "{{ overseerr_image }}:{{ overseerr_image_tag }}"
    network: "{{ overseerr_name }}.network"
    env: "{{ overseerr_container_env_combined }}"
    secrets: "{{ overseerr_container_secrets_combined }}"
    volumes:
      - "{{ overseerr_volume_config }}://app/config"
    publish: "{{ overseerr_traefik_enable | ternary(omit, overseerr_ports) }}"
    labels: "{{ overseerr_container_labels_combined }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ overseerr_quadlet_options_combined }}"
    state: quadlet
  notify: Restart {{ overseerr_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
