---
# vars file for jaredhocutt.homelab.sabnzbd

###############################################################################
# Envrionment
###############################################################################

sabnzbd_container_env_defaults: {}

sabnzbd_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(sabnzbd_container_env_defaults, recursive=True)
  | combine(sabnzbd_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

sabnzbd_secrets_defaults: {}

sabnzbd_secrets_combined: >-
  {{ sabnzbd_secrets_defaults
  | combine(sabnzbd_secrets, recursive=True) }}

sabnzbd_container_secrets_defaults: []

sabnzbd_container_secrets_combined: >-
  {{ sabnzbd_container_secrets_defaults
  + sabnzbd_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

sabnzbd_container_labels_defaults: >
  {{ sabnzbd_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', sabnzbd_name, sabnzbd_traefik_host, '8080'), {}) }}

sabnzbd_container_labels_combined: >-
  {{ sabnzbd_container_labels_defaults
  | combine(sabnzbd_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

sabnzbd_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

sabnzbd_quadlet_options_combined: >-
  {{ sabnzbd_quadlet_options_defaults
  + sabnzbd_quadlet_options }}
