---
# vars file for jaredhocutt.homelab.sabnzbd

###############################################################################
# Envrionment
###############################################################################

sabnzbd_container_env_base: {}

sabnzbd_container_env_combined: >-
  {{ common_container_env_base
  | combine(sabnzbd_container_env_base, recursive=True)
  | combine(sabnzbd_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

sabnzbd_secrets_base: {}

sabnzbd_secrets_combined: >-
  {{ sabnzbd_secrets_base
  | combine(sabnzbd_secrets, recursive=True) }}

sabnzbd_container_secrets_base: []

sabnzbd_container_secrets_combined: >-
  {{ sabnzbd_container_secrets_base
  + sabnzbd_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
sabnzbd_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ sabnzbd_name }}.rule
    value: Host(`{{ sabnzbd_traefik_host }}`)
  - key: traefik.http.routers.{{ sabnzbd_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
sabnzbd_container_labels_base: "{{ sabnzbd_traefik_enable | ternary((sabnzbd_container_labels_traefik | items2dict), {}) }}"

sabnzbd_container_labels_combined: >-
  {{ sabnzbd_container_labels_base
  | combine(sabnzbd_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

sabnzbd_quadlet_options_base: "{{ common_quadlet_options_base }}"

sabnzbd_quadlet_options_combined: >-
  {{ sabnzbd_quadlet_options_base
  + sabnzbd_quadlet_options }}
