---
# vars file for jaredhocutt.homelab.sabnzbd

###############################################################################
# Envrionment
###############################################################################

sabnzbd_container_env_defaults: {}

sabnzbd_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(sabnzbd_container_env_defaults, recursive=True)
  | combine(sabnzbd_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

sabnzbd_secrets_defaults: {}

sabnzbd_secrets_combined: >-
  {{ sabnzbd_secrets_defaults
  | combine(sabnzbd_secrets, recursive=True) }}

sabnzbd_container_secrets_defaults: []

sabnzbd_container_secrets_combined: >-
  {{ sabnzbd_container_secrets_defaults
  + sabnzbd_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
sabnzbd_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ sabnzbd_name }}.rule
    value: Host(`{{ sabnzbd_traefik_host }}`)
  - key: traefik.http.routers.{{ sabnzbd_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ sabnzbd_name }}.loadbalancer.server.port
    value: "8080"
sabnzbd_container_labels_defaults: "{{ sabnzbd_traefik_enable | ternary((sabnzbd_container_labels_traefik | items2dict), {}) }}"

sabnzbd_container_labels_combined: >-
  {{ sabnzbd_container_labels_defaults
  | combine(sabnzbd_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

sabnzbd_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

sabnzbd_quadlet_options_combined: >-
  {{ sabnzbd_quadlet_options_defaults
  + sabnzbd_quadlet_options }}
