---
# defaults file for jaredhocutt.homelab.archiveium

archiveium_name: archiveium

archiveium_image: docker.io/archiveium/archiveium
archiveium_image_tag: latest
archiveium_postgres_image: docker.io/library/postgres
archiveium_postgres_image_tag: "13"
archiveium_minio_image: docker.io/minio/minio
archiveium_minio_image_tag: latest
archiveium_redis_image: docker.io/library/redis
archiveium_redis_image_tag: "7"
archiveium_meilisearch_image: docker.io/getmeili/meilisearch
archiveium_meilisearch_image_tag: latest

archiveium_volume_config: "{{ archiveium_name }}-config"
archiveium_postgres_volume_data: "{{ archiveium_name }}-postgres-data"
archiveium_minio_volume_data: "{{ archiveium_name }}-minio-data"
archiveium_redis_volume_data: "{{ archiveium_name }}-redis-data"
archiveium_meilisearch_volume_data: "{{ archiveium_name }}-meilisearch-data"

archiveium_traefik_enable: true
archiveium_traefik_host: "{{ archiveium_name }}.{{ common_traefik_domain }}"
archiveium_meilisearch_traefik_host: "{{ archiveium_name }}-meilisearch.{{ common_traefik_domain }}"
archiveium_ports:
  - 5292:3000
archiveium_meilisearch_ports:
  - 7700:7700

archiveium_secrets: {}

archiveium_container_env: {}
archiveium_container_secrets: []
archiveium_container_labels: {}
archiveium_quadlet_options: []

archiveium_cron_container_env: {}
archiveium_cron_container_secrets: []
archiveium_cron_container_labels: {}
archiveium_cron_quadlet_options: []

archiveium_postgres_container_env: {}
archiveium_postgres_container_secrets: []
archiveium_postgres_container_labels: {}
archiveium_postgres_quadlet_options: []

archiveium_minio_container_env: {}
archiveium_minio_container_secrets: []
archiveium_minio_container_labels: {}
archiveium_minio_quadlet_options: []

archiveium_redis_container_env: {}
archiveium_redis_container_secrets: []
archiveium_redis_container_labels: {}
archiveium_redis_quadlet_options: []

archiveium_meilisearch_container_env: {}
archiveium_meilisearch_container_secrets: []
archiveium_meilisearch_container_labels: {}
archiveium_meilisearch_quadlet_options: []

archiveium_url: https://{{ archiveium_traefik_host }}
