---
# vars file for jaredhocutt.homelab.warracker

warracker_postgres_db_name: warracker
warracker_postgres_user: warracker

###############################################################################
# Envrionment Variables
###############################################################################

warracker_env_vars_base_custom:
  DB_HOST: "{{ warracker_name }}-postgres"
  DB_PORT: "5432"
  DB_NAME: "{{ warracker_postgres_db_name }}"
  DB_USER: "{{ warracker_postgres_user }}"
  DB_PASSWORD: "{{ warracker_postgres_password }}"
  SECRET_KEY: "{{ warracker_secret_key }}"
  FRONTEND_URL: "{{ warracker_url }}"
  APP_BASE_URL: "{{ warracker_url }}"
  PYTHONUNBUFFERED: "1"
warracker_env_vars_base: "{{ common_env_vars_base | combine(warracker_env_vars_base_custom, recursive=True) }}"

warracker_postgres_env_vars_base_custom:
  POSTGRES_DB: "{{ warracker_postgres_db_name }}"
  POSTGRES_USER: "{{ warracker_postgres_user }}"
  POSTGRES_PASSWORD: "{{ warracker_postgres_password }}"
warracker_postgres_env_vars_base: "{{ common_env_vars_base | combine(warracker_postgres_env_vars_base_custom, recursive=True) }}"

###############################################################################
# Container Labels
###############################################################################

warracker_container_labels_traefik:
  traefik.enable: true
  traefik.http.routers.{{ warracker_name }}.rule: Host(`{{ warracker_traefik_host }}`)
  traefik.http.routers.{{ warracker_name }}.entrypoints: "{{ common_traefik_entrypoint }}"
warracker_container_labels_base: "{{ warracker_traefik_enable | ternary(warracker_container_labels_traefik, {}) }}"

warracker_postgres_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

warracker_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ warracker_name }}-postgres.service
    After={{ warracker_name }}-postgres.service
warracker_quadlet_options_base: "{{ common_quadlet_options_base + warracker_quadlet_options_base_custom }}"

warracker_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"
