---
# vars file for jaredhocutt.homelab.warracker

warracker_postgres_db_name: warracker
warracker_postgres_user: warracker

###############################################################################
# Envrionment Variables
###############################################################################

warracker_env_vars_base:
  DB_HOST: "{{ warracker_name }}-postgres"
  DB_PORT: "5432"
  FRONTEND_URL: "{{ warracker_url }}"
  APP_BASE_URL: "{{ warracker_url }}"
  PYTHONUNBUFFERED: "1"

warracker_postgres_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

warracker_secrets_base:
  warracker_postgres_db_name: "{{ warracker_postgres_db_name }}"
  warracker_postgres_user: "{{ warracker_postgres_user }}"
  warracker_postgres_password: "{{ warracker_postgres_password }}"
  warracker_secret_key: "{{ warracker_secret_key }}"

warracker_secrets_combined: >-
  {{ warracker_secrets_base
  | combine(warracker_secrets, recursive=True) }}

warracker_container_secrets_base:
  - warracker_postgres_db_name,type=env,target=DB_NAME
  - warracker_postgres_user,type=env,target=DB_USER
  - warracker_postgres_password,type=env,target=DB_PASSWORD
  - warracker_secret_key,type=env,target=SECRET_KEY

warracker_postgres_container_secrets_base:
  - warracker_postgres_db_name,type=env,target=POSTGRES_DB
  - warracker_postgres_user,type=env,target=POSTGRES_USER
  - warracker_postgres_password,type=env,target=POSTGRES_PASSWORD

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
warracker_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ warracker_name }}.rule
    value: Host(`{{ warracker_traefik_host }}`)
  - key: traefik.http.routers.{{ warracker_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
warracker_container_labels_base: "{{ warracker_traefik_enable | ternary((warracker_container_labels_traefik | items2dict), {}) }}"

warracker_postgres_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

warracker_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ warracker_name }}-postgres.service
    After={{ warracker_name }}-postgres.service
warracker_quadlet_options_base: "{{ common_quadlet_options_base + warracker_quadlet_options_base_custom }}"

warracker_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"
