---
# defaults file for jaredhocutt.homelab.overseerr

overseerr_name: overseerr

overseerr_image: docker.io/sctx/overseerr
overseerr_image_tag: latest

overseerr_volume_config: "{{ overseerr_name }}-config"

overseerr_traefik_enable: true
overseerr_traefik_host: "{{ overseerr_name }}.{{ common_traefik_domain }}"
overseerr_ports:
  - 5055:5055

overseerr_env_vars: {}

overseerr_secrets: {}
overseerr_container_secrets: []

overseerr_container_labels: {}

overseerr_quadlet_options: []
