---
# vars file for jaredhocutt.homelab.traefik

traefik_command_base:
  - --entrypoints.web.address=:80
  - --entrypoints.web.http.redirections.entrypoint.to=websecure
  - --entrypoints.web.http.redirections.entrypoint.scheme=https
  - --entrypoints.web.http.redirections.entrypoint.permanent=true
  - --entrypoints.websecure.address=:443
  # File provider for dynamic configuration (TLS, external services, etc.)
  - --providers.file.directory=/dynamic
  - --providers.file.watch=true
  # Providers
  - --providers.docker=true
  - --providers.docker.exposedbydefault=false
  - --providers.docker.network={{ traefik_name }}
  # API & Dashboard
  - --api.dashboard=true
  # Observability
  - --log.level={{ traefik_log_level | default('INFO') }}
  - --accesslog=true

###############################################################################
# Envrionment
###############################################################################

traefik_container_env_defaults: {}

traefik_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(traefik_container_env_defaults, recursive=True)
  | combine(traefik_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

traefik_secrets_defaults: {}

traefik_secrets_combined: >-
  {{ traefik_secrets_defaults
  | combine(traefik_secrets, recursive=True) }}

traefik_container_secrets_defaults: []

traefik_container_secrets_combined: >-
  {{ traefik_container_secrets_defaults
  + traefik_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
traefik_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ traefik_name }}.rule
    value: Host(`{{ traefik_traefik_host }}`)
  - key: traefik.http.routers.{{ traefik_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.routers.{{ traefik_name }}.service
    value: api@internal
traefik_container_labels_defaults: "{{ traefik_traefik_enable | ternary((traefik_container_labels_traefik | items2dict), {}) }}"

traefik_container_labels_combined: >-
  {{ traefik_container_labels_defaults
  | combine(traefik_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

traefik_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

traefik_quadlet_options_combined: >-
  {{ traefik_quadlet_options_defaults
  + traefik_quadlet_options }}
