---
# vars file for jaredhocutt.homelab.calibre

###############################################################################
# Envrionment Variables
###############################################################################

calibre_env_vars_base: "{{ common_env_vars_base }}"

###############################################################################
# Container Labels
###############################################################################

calibre_container_labels_traefik:
  traefik.enable: true
  traefik.http.routers.{{ calibre_name }}.rule: Host(`{{ calibre_traefik_host }}`)
  traefik.http.routers.{{ calibre_name }}.entrypoints: "{{ common_traefik_entrypoint }}"
calibre_container_labels_base: "{{ calibre_traefik_enable | ternary(calibre_container_labels_traefik, {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

calibre_quadlet_options_base: "{{ common_quadlet_options_base }}"
