---
# vars file for jaredhocutt.homelab.calibre

###############################################################################
# Envrionment
###############################################################################

calibre_container_env_base: {}

calibre_container_env_combined: >-
  {{ common_container_env_base
  | combine(calibre_container_env_base, recursive=True)
  | combine(calibre_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

calibre_secrets_base: {}

calibre_secrets_combined: >-
  {{ calibre_secrets_base
  | combine(calibre_secrets, recursive=True) }}

calibre_container_secrets_base: []

calibre_container_secrets_combined: >-
  {{ calibre_container_secrets_base
  + calibre_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
calibre_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ calibre_name }}.rule
    value: Host(`{{ calibre_traefik_host }}`)
  - key: traefik.http.routers.{{ calibre_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
calibre_container_labels_base: "{{ calibre_traefik_enable | ternary((calibre_container_labels_traefik | items2dict), {}) }}"

calibre_container_labels_combined: >-
  {{ calibre_container_labels_base
  | combine(calibre_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

calibre_quadlet_options_base: "{{ common_quadlet_options_base }}"

calibre_quadlet_options_combined: >-
  {{ calibre_quadlet_options_base
  + calibre_quadlet_options }}
