---
# vars file for jaredhocutt.homelab.calibre

###############################################################################
# Envrionment
###############################################################################

calibre_container_env_defaults: {}

calibre_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(calibre_container_env_defaults, recursive=True)
  | combine(calibre_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

calibre_secrets_defaults: {}

calibre_secrets_combined: >-
  {{ calibre_secrets_defaults
  | combine(calibre_secrets, recursive=True) }}

calibre_container_secrets_defaults: []

calibre_container_secrets_combined: >-
  {{ calibre_container_secrets_defaults
  + calibre_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

calibre_container_labels_defaults: >
  {{ calibre_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', calibre_name, calibre_traefik_host, '8080'), {}) }}

calibre_container_labels_combined: >-
  {{ calibre_container_labels_defaults
  | combine(calibre_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

calibre_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

calibre_quadlet_options_combined: >-
  {{ calibre_quadlet_options_defaults
  + calibre_quadlet_options }}
