---
# vars file for jaredhocutt.homelab.healthchecks

###############################################################################
# Envrionment
###############################################################################

healthchecks_container_env_defaults:
  SITE_ROOT: "{{ healthchecks_url }}"
  SITE_NAME: "{{ healthchecks_site_name }}"
  SUPERUSER_EMAIL: "{{ healthchecks_email }}"
  DEBUG: "False"

healthchecks_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(healthchecks_container_env_defaults, recursive=True)
  | combine(healthchecks_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

healthchecks_secrets_defaults:
  healthchecks_password: "{{ healthchecks_password }}"
  healthchecks_secret_key: "{{ healthchecks_secret_key }}"

healthchecks_secrets_combined: >-
  {{ healthchecks_secrets_defaults
  | combine(healthchecks_secrets, recursive=True) }}

healthchecks_container_secrets_defaults:
  - healthchecks_password,type=env,target=SUPERUSER_PASSWORD
  - healthchecks_secret_key,type=env,target=SECRET_KEY

healthchecks_container_secrets_combined: >-
  {{ healthchecks_container_secrets_defaults
  + healthchecks_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

healthchecks_container_labels_defaults: >
  {{ healthchecks_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', healthchecks_name, healthchecks_traefik_host, '8000'), {}) }}

healthchecks_container_labels_combined: >-
  {{ healthchecks_container_labels_defaults
  | combine(healthchecks_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

healthchecks_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

healthchecks_quadlet_options_combined: >-
  {{ healthchecks_quadlet_options_defaults
  + healthchecks_quadlet_options }}
