---
# vars file for jaredhocutt.homelab.healthchecks

###############################################################################
# Envrionment
###############################################################################

healthchecks_container_env_defaults:
  SITE_ROOT: "{{ healthchecks_url }}"
  SITE_NAME: "{{ healthchecks_site_name }}"
  SUPERUSER_EMAIL: "{{ healthchecks_email }}"
  DEBUG: "False"

healthchecks_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(healthchecks_container_env_defaults, recursive=True)
  | combine(healthchecks_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

healthchecks_secrets_defaults:
  healthchecks_password: "{{ healthchecks_password }}"
  healthchecks_secret_key: "{{ healthchecks_secret_key }}"

healthchecks_secrets_combined: >-
  {{ healthchecks_secrets_defaults
  | combine(healthchecks_secrets, recursive=True) }}

healthchecks_container_secrets_defaults:
  - healthchecks_password,type=env,target=SUPERUSER_PASSWORD
  - healthchecks_secret_key,type=env,target=SECRET_KEY

healthchecks_container_secrets_combined: >-
  {{ healthchecks_container_secrets_defaults
  + healthchecks_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
healthchecks_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ healthchecks_name }}.rule
    value: Host(`{{ healthchecks_traefik_host }}`)
  - key: traefik.http.routers.{{ healthchecks_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ healthchecks_name }}.loadbalancer.server.port
    value: "8000"
healthchecks_container_labels_defaults: "{{ healthchecks_traefik_enable | ternary((healthchecks_container_labels_traefik | items2dict), {}) }}"

healthchecks_container_labels_combined: >-
  {{ healthchecks_container_labels_defaults
  | combine(healthchecks_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

healthchecks_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

healthchecks_quadlet_options_combined: >-
  {{ healthchecks_quadlet_options_defaults
  + healthchecks_quadlet_options }}
