---
# vars file for jaredhocutt.homelab.healthchecks

###############################################################################
# Envrionment Variables
###############################################################################

healthchecks_env_vars_base:
  SITE_ROOT: "{{ healthchecks_url }}"
  SITE_NAME: "{{ healthchecks_site_name }}"
  SUPERUSER_EMAIL: "{{ healthchecks_email }}"
  SUPERUSER_PASSWORD: "{{ healthchecks_password }}"

###############################################################################
# Secrets
###############################################################################

healthchecks_secrets_base: {}

healthchecks_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
healthchecks_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ healthchecks_name }}.rule
    value: Host(`{{ healthchecks_traefik_host }}`)
  - key: traefik.http.routers.{{ healthchecks_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
healthchecks_container_labels_base: "{{ healthchecks_traefik_enable | ternary((healthchecks_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

healthchecks_quadlet_options_base: "{{ common_quadlet_options_base }}"
