---
# tasks file for jaredhocutt.homelab.healthchecks

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ healthchecks_image }}"
      image_tag: "{{ healthchecks_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ healthchecks_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ healthchecks_volume_config }}"
      options: "{{ healthchecks_volume_config_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  no_log: true
  loop: "{{ healthchecks_secrets_combined | dict2items }}"

- name: Create healthchecks container
  containers.podman.podman_container:
    name: "{{ healthchecks_name }}"
    image: "{{ healthchecks_image }}:{{ healthchecks_image_tag }}"
    network:
      - "{{ healthchecks_name }}.network"
      - "{{ healthchecks_traefik_enable | ternary(common_traefik_network ~ '.network', omit) }}"
    env: >-
      {{ common_env_vars_base
      | combine(healthchecks_env_vars_base, recursive=True)
      | combine(healthchecks_env_vars, recursive=True) }}
    secrets: >-
      {{ healthchecks_container_secrets_base
      + healthchecks_container_secrets }}
    volumes:
      - "{{ healthchecks_volume_config }}:/config"
    publish: "{{ healthchecks_traefik_enable | ternary(omit, healthchecks_ports) }}"
    labels: "{{ healthchecks_container_labels_base | combine(healthchecks_container_labels, recursive=True) }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ healthchecks_quadlet_options_base + healthchecks_quadlet_options }}"
    state: quadlet
  notify: Restart {{ healthchecks_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
