---
# defaults file for jaredhocutt.homelab.audiobookshelf

audiobookshelf_name: audiobookshelf

audiobookshelf_image: ghcr.io/advplyr/audiobookshelf
audiobookshelf_image_tag: latest

audiobookshelf_volume_config: "{{ audiobookshelf_name }}-config"
audiobookshelf_volume_metadata: "{{ audiobookshelf_name }}-metadata"
audiobookshelf_volume_media: "{{ audiobookshelf_name }}-media"

audiobookshelf_traefik_enable: true
audiobookshelf_traefik_host: "{{ audiobookshelf_name }}.{{ common_traefik_domain }}"
audiobookshelf_ports:
  - 13378:80

audiobookshelf_env_vars: {}

audiobookshelf_secrets: {}
audiobookshelf_container_secrets: []

audiobookshelf_container_labels: {}

audiobookshelf_quadlet_options: []
