---
# defaults file for jaredhocutt.homelab.radarr

radarr_name: radarr

radarr_image: lscr.io/linuxserver/radarr
radarr_image_tag: latest

radarr_volume_config: "{{ radarr_name }}-config"
radarr_volume_download: "{{ radarr_name }}-download"
radarr_volume_media: "{{ radarr_name }}-media"

radarr_traefik_enable: true
radarr_traefik_host: "{{ radarr_name }}.{{ common_traefik_domain }}"
radarr_ports:
  - 7878:7878

radarr_secrets: {}

radarr_container_env: {}
radarr_container_secrets: []
radarr_container_labels: {}
radarr_quadlet_options: []
