---
# defaults file for jaredhocutt.homelab.paperless

paperless_name: paperless

paperless_image: ghcr.io/paperless-ngx/paperless-ngx
paperless_image_tag: latest
paperless_postgres_image: docker.io/library/postgres
paperless_postgres_image_tag: "18"
paperless_redis_image: docker.io/library/redis
paperless_redis_image_tag: "8"
paperless_gotenberg_image: docker.io/gotenberg/gotenberg
paperless_gotenberg_image_tag: latest
paperless_tika_image: docker.io/apache/tika
paperless_tika_image_tag: latest-full
paperless_ai_image: docker.io/clusterzx/paperless-ai
paperless_ai_image_tag: latest

paperless_volume_data: "{{ paperless_name }}-data"
paperless_volume_media: "{{ paperless_name }}-media"
paperless_volume_export: "{{ paperless_name }}-export"
paperless_volume_consume: "{{ paperless_name }}-consume"
paperless_postgres_volume_data: "{{ paperless_name }}-postgres-data"
paperless_redis_volume_data: "{{ paperless_name }}-redis-data"
paperless_ai_volume_data: "{{ paperless_name }}-ai-data"

paperless_traefik_enable: true
paperless_traefik_host: "{{ paperless_name }}.{{ common_traefik_domain }}"
paperless_ai_traefik_host: "{{ paperless_name }}-ai.{{ common_traefik_domain }}"
paperless_ports:
  - 8000:8000
paperless_ai_ports:
  - 3000:3000

paperless_env_vars: {}
paperless_postgres_env_vars: {}
paperless_redis_env_vars: {}
paperless_gotenberg_env_vars: {}
paperless_tika_env_vars: {}
paperless_ai_env_vars: {}

paperless_container_labels: {}
paperless_postgres_container_labels: {}
paperless_redis_container_labels: {}
paperless_gotenberg_container_labels: {}
paperless_tika_container_labels: {}
paperless_ai_container_labels: {}

paperless_quadlet_options: []
paperless_postgres_quadlet_options: []
paperless_redis_quadlet_options: []
paperless_gotenberg_quadlet_options: []
paperless_tika_quadlet_options: []
paperless_ai_quadlet_options: []

paperless_task_workers: 1
