---
# defaults file for jaredhocutt.homelab.vault

vault_name: vault

vault_image: docker.io/hashicorp/vault
vault_image_tag: latest

vault_volume_config: "{{ vault_name }}-config"
vault_volume_data: "{{ vault_name }}-data"
vault_volume_logs: "{{ vault_name }}-logs"

vault_traefik_enable: true
vault_traefik_host: "{{ vault_name }}.{{ common_traefik_domain }}"
vault_ports:
  - 8200:8200

vault_container_env: {}

vault_secrets: {}
vault_container_secrets: []

vault_container_labels: {}

vault_quadlet_options: []
