---
# defaults file for jaredhocutt.homelab.tautulli

tautulli_name: tautulli

tautulli_image: lscr.io/linuxserver/tautulli
tautulli_image_tag: latest

tautulli_volume_config: "{{ tautulli_name }}-config"

tautulli_traefik_enable: true
tautulli_traefik_host: "{{ tautulli_name }}.{{ common_traefik_domain }}"
tautulli_ports:
  - 8181:8181

tautulli_env_vars: {}

tautulli_container_labels: {}

tautulli_quadlet_options: []
