---
# vars file for jaredhocutt.homelab.kometa

###############################################################################
# Envrionment
###############################################################################

kometa_container_env_defaults: {}

kometa_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(kometa_container_env_defaults, recursive=True)
  | combine(kometa_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

kometa_secrets_defaults: {}

kometa_secrets_combined: >-
  {{ kometa_secrets_defaults
  | combine(kometa_secrets, recursive=True) }}

kometa_container_secrets_defaults: []

kometa_container_secrets_combined: >-
  {{ kometa_container_secrets_defaults
  + kometa_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

kometa_container_labels_defaults: {}

kometa_container_labels_combined: >-
  {{ kometa_container_labels_defaults
  | combine(kometa_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

kometa_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

kometa_quadlet_options_combined: >-
  {{ kometa_quadlet_options_defaults
  + kometa_quadlet_options }}
