---
# vars file for jaredhocutt.homelab.kometa

###############################################################################
# Envrionment Variables
###############################################################################

kometa_env_vars_base: "{{ common_env_vars_base }}"

###############################################################################
# Container Labels
###############################################################################

kometa_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

kometa_quadlet_options_base: "{{ common_quadlet_options_base }}"
