---
# vars file for jaredhocutt.homelab.homarr

###############################################################################
# Envrionment Variables
###############################################################################

homarr_env_vars_base_custom:
  SECRET_ENCRYPTION_KEY: "{{ homarr_secret_encryption_key }}"
homarr_env_vars_base: "{{ common_env_vars_base | combine(homarr_env_vars_base_custom, recursive=True) }}"

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
homarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ homarr_name }}.rule
    value: Host(`{{ homarr_traefik_host }}`)
  - key: traefik.http.routers.{{ homarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
homarr_container_labels_base: "{{ homarr_traefik_enable | ternary((homarr_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

homarr_quadlet_options_base: "{{ common_quadlet_options_base }}"
