---
# vars file for jaredhocutt.homelab.homarr

###############################################################################
# Envrionment
###############################################################################

homarr_container_env_defaults: {}

homarr_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(homarr_container_env_defaults, recursive=True)
  | combine(homarr_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

homarr_secrets_defaults:
  homarr_secret_encryption_key: "{{ homarr_secret_encryption_key }}"

homarr_secrets_combined: >-
  {{ homarr_secrets_defaults
  | combine(homarr_secrets, recursive=True) }}

homarr_container_secrets_defaults:
  - homarr_secret_encryption_key,type=env,target=SECRET_ENCRYPTION_KEY

homarr_container_secrets_combined: >-
  {{ homarr_container_secrets_defaults
  + homarr_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
homarr_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ homarr_name }}.rule
    value: Host(`{{ homarr_traefik_host }}`)
  - key: traefik.http.routers.{{ homarr_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ homarr_name }}.loadbalancer.server.port
    value: "7575"
homarr_container_labels_defaults: "{{ homarr_traefik_enable | ternary((homarr_container_labels_traefik | items2dict), {}) }}"

homarr_container_labels_combined: >-
  {{ homarr_container_labels_defaults
  | combine(homarr_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

homarr_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

homarr_quadlet_options_combined: >-
  {{ homarr_quadlet_options_defaults
  + homarr_quadlet_options }}
