---
# vars file for jaredhocutt.homelab.n8n

n8n_postgres_db_name: n8n
n8n_postgres_user: n8n

###############################################################################
# Envrionment
###############################################################################

n8n_env_base:
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: "{{ n8n_name }}-postgres"
  DB_POSTGRESDB_PORT: "5432"
  N8N_DIAGNOSTICS_ENABLED: "false"
  WEBHOOK_URL: "{{ n8n_url }}"
  N8N_PROXY_HOPS: "1"
  EXECUTIONS_MODE: queue
  QUEUE_BULL_REDIS_HOST: "{{ n8n_name }}-redis"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"

n8n_worker_env_base: "{{ n8n_env_vars_base }}"

n8n_postgres_env_base: {}

n8n_redis_env_base: {}

###############################################################################
# Secrets
###############################################################################

n8n_secrets_defaults:
  n8n_postgres_db_name: "{{ n8n_postgres_db_name }}"
  n8n_postgres_user: "{{ n8n_postgres_user }}"
  n8n_postgres_password: "{{ n8n_postgres_password }}"

n8n_secrets_combined: >-
  {{ n8n_secrets_defaults
  | combine(n8n_secrets, recursive=True) }}

n8n_container_secrets_defaults:
  - n8n_postgres_db_name,type=env,target=DB_POSTGRESDB_DATABASE
  - n8n_postgres_user,type=env,target=DB_POSTGRESDB_USER
  - n8n_postgres_password,type=env,target=DB_POSTGRESDB_PASSWORD

n8n_worker_container_secrets_defaults: "{{ n8n_container_secrets_defaults }}"

n8n_postgres_container_secrets_defaults:
  - n8n_postgres_db_name,type=env,target=POSTGRES_DB
  - n8n_postgres_user,type=env,target=POSTGRES_USER
  - n8n_postgres_password,type=env,target=POSTGRES_PASSWORD

n8n_redis_container_secrets_defaults: []

n8n_container_secrets_combined: >-
  {{ n8n_container_secrets_defaults
  + n8n_container_secrets }}
n8n_worker_container_secrets_combined: >-
  {{ n8n_worker_container_secrets_defaults
  + n8n_worker_container_secrets }}
n8n_postgres_container_secrets_combined: >-
  {{ n8n_postgres_container_secrets_defaults
  + n8n_postgres_container_secrets }}
n8n_redis_container_secrets_combined: >-
  {{ n8n_redis_container_secrets_defaults
  + n8n_redis_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

n8n_container_labels_defaults: >
  {{ n8n_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', n8n_name, n8n_traefik_host, '5678'), {}) }}

n8n_worker_container_labels_defaults: {}

n8n_postgres_container_labels_defaults: {}

n8n_redis_container_labels_defaults: {}

n8n_container_labels_combined: >-
  {{ n8n_container_labels_defaults
  | combine(n8n_container_labels, recursive=True) }}
n8n_worker_container_labels_combined: >-
  {{ n8n_worker_container_labels_defaults
  | combine(n8n_worker_container_labels, recursive=True) }}
n8n_postgres_container_labels_combined: >-
  {{ n8n_postgres_container_labels_defaults
  | combine(n8n_postgres_container_labels, recursive=True) }}
n8n_redis_container_labels_combined: >-
  {{ n8n_redis_container_labels_defaults
  | combine(n8n_redis_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

n8n_quadlet_options_depends:
  - |
    [Unit]
    Requires={{ n8n_name }}-postgres.service
    Requires={{ n8n_name }}-redis.service
    After={{ n8n_name }}-postgres.service
    After={{ n8n_name }}-redis.service
n8n_quadlet_options_defaults: "{{ common_quadlet_options_defaults + n8n_quadlet_options_depends }}"

n8n_worker_quadlet_options_depends:
  - |
    [Unit]
    Requires={{ n8n_name }}.service
    Requires={{ n8n_name }}-postgres.service
    Requires={{ n8n_name }}-redis.service
    After={{ n8n_name }}.service
    After={{ n8n_name }}-postgres.service
    After={{ n8n_name }}-redis.service
n8n_worker_quadlet_options_defaults: "{{ common_quadlet_options_defaults + n8n_worker_quadlet_options_depends }}"

n8n_postgres_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

n8n_redis_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

n8n_quadlet_options_combined: >-
  {{ n8n_quadlet_options_defaults
  + n8n_quadlet_options }}
n8n_worker_quadlet_options_combined: >-
  {{ n8n_worker_quadlet_options_defaults
  + n8n_worker_quadlet_options }}
n8n_postgres_quadlet_options_combined: >-
  {{ n8n_postgres_quadlet_options_defaults
  + n8n_postgres_quadlet_options }}
n8n_redis_quadlet_options_combined: >-
  {{ n8n_redis_quadlet_options_defaults
  + n8n_redis_quadlet_options }}
