---
# vars file for jaredhocutt.homelab.n8n

n8n_postgres_db_name: n8n
n8n_postgres_user: n8n

###############################################################################
# Envrionment Variables
###############################################################################

n8n_env_vars_base:
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: "{{ n8n_name }}-postgres"
  DB_POSTGRESDB_PORT: "5432"
  N8N_DIAGNOSTICS_ENABLED: "false"

n8n_postgres_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

n8n_secrets_base:
  n8n_postgres_db_name: "{{ n8n_postgres_db_name }}"
  n8n_postgres_user: "{{ n8n_postgres_user }}"
  n8n_postgres_password: "{{ n8n_postgres_password }}"

n8n_container_secrets_base:
  - n8n_postgres_db_name,type=env,target=DB_POSTGRESDB_DATABASE
  - n8n_postgres_user,type=env,target=DB_POSTGRESDB_USER
  - n8n_postgres_password,type=env,target=DB_POSTGRESDB_PASSWORD

n8n_postgres_container_secrets_base:
  - n8n_postgres_db_name,type=env,target=POSTGRES_DB
  - n8n_postgres_user,type=env,target=POSTGRES_USER
  - n8n_postgres_password,type=env,target=POSTGRES_PASSWORD

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
n8n_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ n8n_name }}.rule
    value: Host(`{{ n8n_traefik_host }}`)
  - key: traefik.http.routers.{{ n8n_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
n8n_container_labels_base: "{{ n8n_traefik_enable | ternary((n8n_container_labels_traefik | items2dict), {}) }}"

n8n_postgres_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

n8n_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ n8n_name }}-postgres.service
    After={{ n8n_name }}-postgres.service
n8n_quadlet_options_base: "{{ common_quadlet_options_base + n8n_quadlet_options_base_custom }}"

n8n_postgres_quadlet_options_base: "{{ common_quadlet_options_base }}"
