---
# vars file for jaredhocutt.homelab.audiobookshelf

###############################################################################
# Envrionment
###############################################################################

audiobookshelf_container_env_defaults: {}

audiobookshelf_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(audiobookshelf_container_env_defaults, recursive=True)
  | combine(audiobookshelf_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

audiobookshelf_secrets_defaults: {}

audiobookshelf_secrets_combined: >-
  {{ audiobookshelf_secrets_defaults
  | combine(audiobookshelf_secrets, recursive=True) }}

audiobookshelf_container_secrets_defaults: []

audiobookshelf_container_secrets_combined: >-
  {{ audiobookshelf_container_secrets_defaults
  + audiobookshelf_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

audiobookshelf_container_labels_defaults: >
  {{ audiobookshelf_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', audiobookshelf_name, audiobookshelf_traefik_host, '80'), {}) }}

audiobookshelf_container_labels_combined: >-
  {{ audiobookshelf_container_labels_defaults
  | combine(audiobookshelf_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

audiobookshelf_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

audiobookshelf_quadlet_options_combined: >-
  {{ audiobookshelf_quadlet_options_defaults
  + audiobookshelf_quadlet_options }}
