---
# vars file for jaredhocutt.homelab.audiobookshelf

###############################################################################
# Envrionment
###############################################################################

audiobookshelf_container_env_defaults: {}

audiobookshelf_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(audiobookshelf_container_env_defaults, recursive=True)
  | combine(audiobookshelf_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

audiobookshelf_secrets_defaults: {}

audiobookshelf_secrets_combined: >-
  {{ audiobookshelf_secrets_defaults
  | combine(audiobookshelf_secrets, recursive=True) }}

audiobookshelf_container_secrets_defaults: []

audiobookshelf_container_secrets_combined: >-
  {{ audiobookshelf_container_secrets_defaults
  + audiobookshelf_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
audiobookshelf_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ audiobookshelf_name }}.rule
    value: Host(`{{ audiobookshelf_traefik_host }}`)
  - key: traefik.http.routers.{{ audiobookshelf_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ audiobookshelf_name }}.loadbalancer.server.port
    value: "80"
audiobookshelf_container_labels_defaults: "{{ audiobookshelf_traefik_enable | ternary((audiobookshelf_container_labels_traefik | items2dict), {}) }}"

audiobookshelf_container_labels_combined: >-
  {{ audiobookshelf_container_labels_defaults
  | combine(audiobookshelf_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

audiobookshelf_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

audiobookshelf_quadlet_options_combined: >-
  {{ audiobookshelf_quadlet_options_defaults
  + audiobookshelf_quadlet_options }}
