---
# vars file for jaredhocutt.homelab.tautulli

###############################################################################
# Envrionment
###############################################################################

tautulli_container_env_base: {}

tautulli_container_env_combined: >-
  {{ common_container_env_base
  | combine(tautulli_container_env_base, recursive=True)
  | combine(tautulli_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

tautulli_secrets_base: {}

tautulli_secrets_combined: >-
  {{ tautulli_secrets_base
  | combine(tautulli_secrets, recursive=True) }}

tautulli_container_secrets_base: []

tautulli_container_secrets_combined: >-
  {{ tautulli_container_secrets_base
  + tautulli_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
tautulli_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.docker.network
    value: "{{ common_traefik_network }}"
  - key: traefik.http.routers.{{ tautulli_name }}.rule
    value: Host(`{{ tautulli_traefik_host }}`)
  - key: traefik.http.routers.{{ tautulli_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
  - key: traefik.http.services.{{ tautulli_name }}.loadbalancer.server.port
    value: "8181"
tautulli_container_labels_base: "{{ tautulli_traefik_enable | ternary((tautulli_container_labels_traefik | items2dict), {}) }}"

tautulli_container_labels_combined: >-
  {{ tautulli_container_labels_base
  | combine(tautulli_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

tautulli_quadlet_options_base: "{{ common_quadlet_options_base }}"

tautulli_quadlet_options_combined: >-
  {{ tautulli_quadlet_options_base
  + tautulli_quadlet_options }}
