---
# vars file for jaredhocutt.homelab.tautulli

###############################################################################
# Envrionment Variables
###############################################################################

tautulli_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

tautulli_secrets_base: {}

tautulli_secrets_combined: >-
  {{ tautulli_secrets_base
  | combine(tautulli_secrets, recursive=True) }}

tautulli_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
tautulli_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ tautulli_name }}.rule
    value: Host(`{{ tautulli_traefik_host }}`)
  - key: traefik.http.routers.{{ tautulli_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
tautulli_container_labels_base: "{{ tautulli_traefik_enable | ternary((tautulli_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

tautulli_quadlet_options_base: "{{ common_quadlet_options_base }}"
