---
# vars file for jaredhocutt.homelab.tautulli

###############################################################################
# Envrionment
###############################################################################

tautulli_container_env_defaults: {}

tautulli_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(tautulli_container_env_defaults, recursive=True)
  | combine(tautulli_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

tautulli_secrets_defaults: {}

tautulli_secrets_combined: >-
  {{ tautulli_secrets_defaults
  | combine(tautulli_secrets, recursive=True) }}

tautulli_container_secrets_defaults: []

tautulli_container_secrets_combined: >-
  {{ tautulli_container_secrets_defaults
  + tautulli_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

tautulli_container_labels_defaults: >
  {{ tautulli_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', tautulli_name, tautulli_traefik_host, '8181'), {}) }}

tautulli_container_labels_combined: >-
  {{ tautulli_container_labels_defaults
  | combine(tautulli_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

tautulli_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

tautulli_quadlet_options_combined: >-
  {{ tautulli_quadlet_options_defaults
  + tautulli_quadlet_options }}
