---
# vars file for jaredhocutt.homelab.changedetection

###############################################################################
# Envrionment Variables
###############################################################################

changedetection_env_vars_base_custom:
  PLAYWRIGHT_DRIVER_URL: "ws://{{ changedetection_name }}-browser:3000"
changedetection_env_vars_base: "{{ common_env_vars_base | combine(changedetection_env_vars_base_custom, recursive=True) }}"

changedetection_browser_env_vars_base_custom:
  SCREEN_WIDTH: "1920"
  SCREEN_HEIGHT: "1024"
  SCREEN_DEPTH: "16"
  MAX_CONCURRENT_CHROME_PROCESSES: "10"
changedetection_browser_env_vars_base: "{{ common_env_vars_base | combine(changedetection_browser_env_vars_base_custom, recursive=True) }}"

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
changedetection_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ changedetection_name }}.rule
    value: Host(`{{ changedetection_traefik_host }}`)
  - key: traefik.http.routers.{{ changedetection_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
changedetection_container_labels_base: "{{ changedetection_traefik_enable | ternary((changedetection_container_labels_traefik | items2dict), {}) }}"

changedetection_browser_container_labels_base: {}

###############################################################################
# Quadlet Options
###############################################################################

changedetection_quadlet_options_base_custom:
  - |
    [Unit]
    Requires={{ changedetection_name }}-browser.service
    After={{ changedetection_name }}-browser.service
changedetection_quadlet_options_base: "{{ common_quadlet_options_base + changedetection_quadlet_options_base_custom }}"

changedetection_browser_quadlet_options_base: "{{ common_quadlet_options_base }}"
