---
# vars file for jaredhocutt.homelab.changedetection

###############################################################################
# Envrionment
###############################################################################

changedetection_container_env_defaults:
  PLAYWRIGHT_DRIVER_URL: "ws://{{ changedetection_name }}-browser:3000"

changedetection_browser_container_env_defaults:
  SCREEN_WIDTH: "1920"
  SCREEN_HEIGHT: "1024"
  SCREEN_DEPTH: "16"
  MAX_CONCURRENT_CHROME_PROCESSES: "10"

changedetection_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(changedetection_container_env_defaults, recursive=True)
  | combine(changedetection_container_env, recursive=True) }}
changedetection_browser_container_env_combined: >-
  {{ common_container_env_defaults
  | combine(changedetection_browser_container_env_defaults, recursive=True)
  | combine(changedetection_browser_container_env, recursive=True) }}

###############################################################################
# Secrets
###############################################################################

changedetection_secrets_defaults: {}

changedetection_secrets_combined: >-
  {{ changedetection_secrets_defaults
  | combine(changedetection_secrets, recursive=True) }}

changedetection_container_secrets_defaults: []

changedetection_browser_container_secrets_defaults: []

changedetection_container_secrets_combined: >-
  {{ changedetection_container_secrets_defaults
  + changedetection_container_secrets }}
changedetection_browser_container_secrets_combined: >-
  {{ changedetection_browser_container_secrets_defaults
  + changedetection_browser_container_secrets }}

###############################################################################
# Container Labels
###############################################################################

changedetection_container_labels_defaults: >
  {{ changedetection_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', changedetection_name, changedetection_traefik_host, '5000'), {}) }}

changedetection_browser_container_labels_defaults: {}

changedetection_container_labels_combined: >-
  {{ changedetection_container_labels_defaults
  | combine(changedetection_container_labels, recursive=True) }}
changedetection_browser_container_labels_combined: >-
  {{ changedetection_browser_container_labels_defaults
  | combine(changedetection_browser_container_labels, recursive=True) }}

###############################################################################
# Quadlet Options
###############################################################################

changedetection_quadlet_options_depends:
  - |
    [Unit]
    Requires={{ changedetection_name }}-browser.service
    After={{ changedetection_name }}-browser.service
changedetection_quadlet_options_defaults: "{{ common_quadlet_options_defaults + changedetection_quadlet_options_depends }}"

changedetection_browser_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

changedetection_quadlet_options_combined: >-
  {{ changedetection_quadlet_options_defaults
  + changedetection_quadlet_options }}
changedetection_browser_quadlet_options_combined: >-
  {{ changedetection_browser_quadlet_options_defaults
  + changedetection_browser_quadlet_options }}
