---
# vars file for jaredhocutt.homelab.vault

vault_uid: 100
vault_gid: 1000

###############################################################################
# Envrionment Variables
###############################################################################

vault_env_vars_base: {}

###############################################################################
# Secrets
###############################################################################

vault_secrets_base: {}

vault_secrets_combined: >-
  {{ vault_secrets_base
  | combine(vault_secrets, recursive=True) }}

vault_container_secrets_base: []

###############################################################################
# Container Labels
###############################################################################

# This is done as a list and converted to a dict in order to use variables in the key name
vault_container_labels_traefik:
  - key: traefik.enable
    value: "true"
  - key: traefik.http.routers.{{ vault_name }}.rule
    value: Host(`{{ vault_traefik_host }}`)
  - key: traefik.http.routers.{{ vault_name }}.entrypoints
    value: "{{ common_traefik_entrypoint }}"
vault_container_labels_base: "{{ vault_traefik_enable | ternary((vault_container_labels_traefik | items2dict), {}) }}"

###############################################################################
# Quadlet Options
###############################################################################

vault_quadlet_options_base: "{{ common_quadlet_options_base }}"
