---

server_setup_packages:
  - chezmoi
  - cockpit
  - cockpit-files
  - cockpit-networkmanager
  - cockpit-podman
  - cockpit-storaged
  - cockpit-system
  - curl
  - dnf5-plugin-automatic
  - git
  - gnupg2
  - htop
  - net-tools
  - pcp
  - python3-pcp
  - rsync
  - stow
  - tmux
  - unzip
  - vim
  - wget
  - zsh

server_setup_enabled_services:
  - cockpit.socket
  - pmlogger.service

global_volume_download: download

global_volume_media: media
global_volume_media_options_device: "{{ lookup('bitwarden.secrets.lookup', bws_uuid.global_storage_host) }}:/mnt/data/media"
global_volume_media_options_type: nfs
global_volume_media_options_options: soft,nfsvers=3
global_volume_media_options:
  - Device={{ global_volume_media_options_device }}
  - Type={{ global_volume_media_options_type }}
  - Options={{ global_volume_media_options_options }}

global_media_uid: "{{ lookup('bitwarden.secrets.lookup', bws_uuid.global_media_uid) }}"
global_media_gid: "{{ lookup('bitwarden.secrets.lookup', bws_uuid.global_media_gid) }}"
