galaxy_info:
  author: Jared Hocutt
  description: calibre_web_automated
  license: MIT

  min_ansible_version: "2.14"

dependencies:
  - role: jaredhocutt.homelab.common
  - role: jaredhocutt.homelab.podman
